(()=>{
 const $=id=>document.getElementById(id),read=()=>{try{return JSON.parse(localStorage.getItem('wonder_preview_state')||'{}')}catch{return{}}},write=s=>{try{localStorage.setItem('wonder_preview_state',JSON.stringify(s))}catch{}};
 const email=$('accountEmail'),phone=$('accountPhone'),password=$('accountPassword'),btn=$('accountContinue'),status=$('accountStatus'),account=$('account');if(!email||!phone||!password||!btn||!account)return;
 password.minLength=10;password.placeholder='At least 10 characters';
 const eyebrow=account.querySelector('.eyebrow');
 let toggle=$('accountModeToggle');if(!toggle){toggle=document.createElement('button');toggle.id='accountModeToggle';toggle.type='button';toggle.className='account-mode-toggle';btn.closest('.actions')?.insertAdjacentElement('afterend',toggle);}let mode='create';const phoneLabel=phone.closest('label');
 const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),normalizePhone=v=>v.replace(/[^\d+]/g,''),showStatus=t=>{status.textContent=t||'';status.style.display=t?'block':'none'};
 function go(id){const target=$(id);if(!target)return;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s===target));const phase=$('phaseLabel');if(phase)phase.textContent={account:'Account',assessment:'Assessment',mirror:'Mirror',home:'Wonder',essentials:'Preferences',visual:'Photos'}[id]||'Wonder';const s=read();s.screen=id;write(s);window.scrollTo(0,0);}
 function setMode(next){mode=next;const signin=mode==='signin';if(phoneLabel)phoneLabel.style.display=signin?'none':'';if(eyebrow)eyebrow.textContent=signin?'Sign in to Wonder':'Create your Wonder account';btn.textContent=signin?'Sign in':'Create account';toggle.textContent=signin?'New to Wonder? Create an account':'Already have an account? Sign in';showStatus('');password.autocomplete=signin?'current-password':'new-password';}
 toggle.onclick=()=>setMode(mode==='signin'?'create':'signin');
 function resetUserScopedState(userId){const previous=read(),previousId=previous.account?.id||null;if(previousId&&previousId===userId)return;localStorage.setItem('wonder_preview_state','{}');localStorage.removeItem('wonder_assessment_v2');localStorage.removeItem('wonder_place_meta');localStorage.removeItem('wonder_match_state_v2');}
 function saveSession(data,{fallbackEmail='',fallbackPhone=''}={}){const u=data.user||{};if(u.id)resetUserScopedState(u.id);const s=read();s.account={...(s.account||{}),id:u.id||s.account?.id||null,email:u.email||fallbackEmail||s.account?.email||'',phone:u.user_metadata?.phone||fallbackPhone||s.account?.phone||'',emailVerified:!!u.email_confirmed_at,phoneVerified:false,persistence:'httpOnly-cookie',createdAt:u.created_at||s.account?.createdAt||new Date().toISOString()};const seconds=Number(data.expires_in||3600);s.auth={mode:'httpOnly-cookie',savedAt:Date.now(),expiresAt:Date.now()+seconds*1000};write(s);window.dispatchEvent(new CustomEvent('wonder-auth-updated'));}
 async function request(action,e,p,pw){const r=await fetch('/api/signup',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email:e,phone:p,password:pw})});const d=await r.json().catch(()=>({}));return{r,d};}
 async function hydrate(){const r=await fetch('/api/persist',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'hydrate'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to restore your Wonder account.');const s=read();if(d.birth)s.birth={dob:d.birth.date_of_birth||'',tob:d.birth.time_of_birth||'',pob:d.birth.place_of_birth||'',toa:d.birth.time_accuracy||'Exact'};if(d.profile)s.essentials={firstName:d.profile.first_name||'',currentCity:d.profile.current_city||'',gender:d.profile.gender||'',interested:d.profile.interested_in||'',intent:d.profile.relationship_intention||'',structure:d.profile.relationship_structure||'Monogamy',children:d.profile.children||'',religion:d.profile.religion||'',ageRange:d.profile.age_range||'',distance:d.profile.max_distance||'25 miles',nonnegotiables:d.profile.nonnegotiables||''};if(d.assessment){s.assessmentV2=d.assessment;s.archetype=d.assessment.mirror?.primary?.name||d.assessment.archetypes?.[0]?.name||null;}write(s);if(d.active_assessment?.session)localStorage.setItem('wonder_assessment_v2',JSON.stringify({responses:d.active_assessment.responses||{},history:[],sessionId:d.active_assessment.session.id,complete:false,cache:{},changedCounts:{}}));else if(d.assessment)localStorage.setItem('wonder_assessment_v2',JSON.stringify({responses:{},history:[],sessionId:d.assessment.assessment_session_id||null,complete:true,cache:{},changedCounts:{},result:d.assessment,snapshotSyncedAt:d.assessment.created_at||new Date().toISOString()}));else localStorage.removeItem('wonder_assessment_v2');return d;}
 function targetAfterSignin(){const s=read();let a={};try{a=JSON.parse(localStorage.getItem('wonder_assessment_v2')||'{}')}catch{}if(a.complete||s.assessmentV2)return s.accuracy||s.correction?'home':'mirror';return'assessment';}
 async function completeAuth(action,e,p,pw){let{r,d}=await request(action,e,p,pw);if(action==='create'&&!r.ok&&d.code==='account_exists'){const retry=await request('signin',e,p,pw);if(retry.r.ok){r=retry.r;d=retry.d;action='signin';}else{setMode('signin');throw new Error('An account already exists for this email. Sign in with its password to continue.');}}if(!r.ok)throw new Error(d.error||'Unable to continue.');saveSession(d,{fallbackEmail:e,fallbackPhone:p});password.value='';if(action==='create'){localStorage.removeItem('wonder_assessment_v2');go('assessment');return;}showStatus('Restoring your Wonder progress…');await hydrate();go(targetAfterSignin());}
 btn.onclick=async()=>{const e=email.value.trim().toLowerCase(),p=normalizePhone(phone.value.trim()),pw=password.value;if(!validEmail(e)){showStatus('Enter a valid email address.');email.focus();return;}if(mode==='create'&&p.replace(/\D/g,'').length<10){showStatus('Enter a valid phone number.');phone.focus();return;}if(pw.length<10){showStatus('Use a password with at least 10 characters.');password.focus();return;}btn.disabled=true;showStatus(mode==='signin'?'Signing you in…':'Creating your Wonder account…');try{await completeAuth(mode,e,p,pw);}catch(err){showStatus(err.message||'Unable to continue.');}finally{btn.disabled=false;}};
 const existing=read();if(existing.account?.email)email.value=existing.account.email||'';if(existing.account?.phone)phone.value=existing.account.phone||'';setMode('create');
 window.wonderAccountGo=go;
})();