(()=>{
 const $=id=>document.getElementById(id),state=()=>{try{return JSON.parse(localStorage.getItem('wonder_preview_state')||'{}')}catch{return{}}},save=s=>{try{localStorage.setItem('wonder_preview_state',JSON.stringify(s))}catch{}};
 const email=$('accountEmail'),phone=$('accountPhone'),password=$('accountPassword'),btn=$('accountContinue'),status=$('accountStatus');if(!email||!phone||!password||!btn)return;
 password.minLength=10;password.placeholder='At least 10 characters';
 let toggle=$('accountModeToggle');if(!toggle){toggle=document.createElement('button');toggle.id='accountModeToggle';toggle.type='button';toggle.className='account-mode-toggle';toggle.textContent='Already have an account? Sign in';btn.closest('.actions')?.insertAdjacentElement('afterend',toggle);}let mode='create';const phoneLabel=phone.closest('label'),existing=state();if(existing.account){email.value=existing.account.email||'';phone.value=existing.account.phone||'';}
 const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),normalizePhone=v=>v.replace(/[^\d+]/g,''),showStatus=t=>{if(status){status.textContent=t||'';status.style.display=t?'block':'none'}};
 function setMode(next){mode=next;if(phoneLabel)phoneLabel.style.display=mode==='signin'?'none':'';btn.textContent=mode==='signin'?'Sign in':'Create account';toggle.textContent=mode==='signin'?'New to Wonder? Create an account':'Already have an account? Sign in';showStatus('');}toggle.onclick=()=>setMode(mode==='signin'?'create':'signin');
 function resetUserScopedState(userId){const previous=state(),previousId=previous.account?.id||null;if(previousId&&previousId===userId)return;localStorage.setItem('wonder_preview_state','{}');localStorage.removeItem('wonder_assessment_v2');localStorage.removeItem('wonder_place_meta');localStorage.removeItem('wonder_match_state_v2');}
 function saveSession(data,{fallbackEmail='',fallbackPhone=''}={}){const u=data.user||{};if(u.id)resetUserScopedState(u.id);const current=state();current.account={...(current.account||{}),id:u.id||current.account?.id||null,email:u.email||fallbackEmail||current.account?.email||'',phone:u.user_metadata?.phone||fallbackPhone||current.account?.phone||'',emailVerified:!!u.email_confirmed_at,phoneVerified:false,persistence:'httpOnly-cookie',createdAt:u.created_at||current.account?.createdAt||new Date().toISOString()};const seconds=Number(data.expires_in||3600);current.auth={mode:'httpOnly-cookie',savedAt:Date.now(),expiresAt:Date.now()+seconds*1000};save(current);window.dispatchEvent(new CustomEvent('wonder-auth-updated'));}
 function cloudTarget(){const s=state();let a={};try{a=JSON.parse(localStorage.getItem('wonder_assessment_v2')||'{}')}catch{}if(a.sessionId&&!a.complete)return'assessment';if(a.complete&&s.assessmentV2)return'mirror';if(s.essentials&&Object.values(s.essentials).some(Boolean))return'visual';if(s.birth&&(s.birth.dob||s.birth.pob||s.birth.tob))return'essentials';return'birth';}
 async function hydrateFromCloud(){try{const r=await fetch('/api/persist',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'hydrate'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to restore your Wonder account.');const s=state();if(d.birth)s.birth={dob:d.birth.date_of_birth||'',tob:d.birth.time_of_birth||'',pob:d.birth.place_of_birth||'',toa:d.birth.time_accuracy||'Exact'};else delete s.birth;if(d.profile)s.essentials={firstName:d.profile.first_name||'',currentCity:d.profile.current_city||'',gender:d.profile.gender||'',interested:d.profile.interested_in||'',intent:d.profile.relationship_intention||'',structure:d.profile.relationship_structure||'Monogamy',children:d.profile.children||'',religion:d.profile.religion||'',ageRange:d.profile.age_range||'',distance:d.profile.max_distance||'25 miles',nonnegotiables:d.profile.nonnegotiables||''};else delete s.essentials;const placeMeta={};if(d.birth?.location_data&&Object.keys(d.birth.location_data).length)placeMeta.birthplace=d.birth.location_data;if(d.profile?.location_data&&Object.keys(d.profile.location_data).length)placeMeta.current_city=d.profile.location_data;if(Object.keys(placeMeta).length)localStorage.setItem('wonder_place_meta',JSON.stringify(placeMeta));else localStorage.removeItem('wonder_place_meta');if(d.assessment){s.assessmentV2=d.assessment;s.archetype=d.assessment.mirror?.primary?.name||d.assessment.archetypes?.[0]?.name||null;}else{delete s.assessmentV2;delete s.archetype;delete s.accuracy;delete s.correction;}save(s);if(d.active_assessment?.session)localStorage.setItem('wonder_assessment_v2',JSON.stringify({responses:d.active_assessment.responses||{},history:[],sessionId:d.active_assessment.session.id,complete:false,cache:{},changedCounts:{}}));else if(d.assessment)localStorage.setItem('wonder_assessment_v2',JSON.stringify({responses:{},history:[],sessionId:d.assessment.assessment_session_id||null,complete:true,cache:{},changedCounts:{},result:d.assessment,snapshotSyncedAt:d.assessment.created_at||new Date().toISOString()}));else localStorage.removeItem('wonder_assessment_v2');return d;}catch(e){console.warn('Wonder cloud hydrate',e);return null;}}
 async function refreshSession(force=false){const s=state(),expires=Number(s.auth?.expiresAt||0);if(!force&&s.auth?.mode==='httpOnly-cookie'&&expires-Date.now()>5*60*1000)return true;try{const r=await fetch('/api/signup',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'refresh'})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error();saveSession(d);return true;}catch{const current=state();delete current.auth;save(current);return false;}}
 btn.onclick=async()=>{const e=email.value.trim().toLowerCase(),p=normalizePhone(phone.value.trim()),pw=password.value;if(!validEmail(e)){showStatus('Enter a valid email address.');email.focus();return;}if(mode==='create'&&p.replace(/\D/g,'').length<10){showStatus('Enter a valid phone number.');phone.focus();return;}if(pw.length<10){showStatus('Use a password with at least 10 characters.');password.focus();return;}btn.disabled=true;showStatus(mode==='signin'?'Signing you in…':'Creating your Wonder account…');try{const response=await fetch('/api/signup',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email:e,phone:p,password:pw})});const data=await response.json().catch(()=>({}));if(!response.ok){if(data.code==='account_exists'){setMode('signin');throw new Error('That account already exists. Enter your password to sign in.');}throw new Error(data.error||'Unable to continue.');}saveSession(data,{fallbackEmail:e,fallbackPhone:p});password.value='';await hydrateFromCloud();setTimeout(()=>show(cloudTarget()),180);}catch(err){showStatus(err.message||'Unable to continue.');}finally{btn.disabled=false;}};
 refreshSession(false);window.addEventListener('focus',()=>refreshSession(false));setInterval(()=>refreshSession(false),10*60*1000);
})();