const screens=[...document.querySelectorAll('.screen')];const phase=document.getElementById('phaseLabel');function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo({top:0,behavior:'smooth'});const labels={welcome:'Private preview',birth:'Origin',assessment:'Assessment',processing:'Mirror',mirror:'Mirror',home:'Wonder',journal:'Journal',ai:'Wonder AI',matches:'Introductions'};phase.textContent=labels[id]||'Wonder'}document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.next;if(n==='processing'){runProcessing()}else show(n)}));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));
const questions=[
{section:'Instinct',q:'You unexpectedly get three days entirely to yourself. Which sounds most appealing?',o:['Gather people and see where the weekend goes.','Disappear into something I’m fascinated by.','Plan a trip or do something I’ve never done.','Catch up, organize my life, and enjoy the quiet.']},
{section:'Instinct',q:'Someone intelligent strongly challenges something you believe. What happens first?',o:['I become curious about what they see that I don’t.','I immediately test their argument for weaknesses.','I defend my position until they demonstrate I’m wrong.','I dislike the conflict more than I care about winning it.']},
{section:'Self',q:'Which would you most want someone you love to say about you?',o:['You make me feel safe.','You make my life larger.','You understand me completely.','I admire who you are.']},
{section:'Self',q:'Which criticism would be hardest to hear from someone whose judgment you respect?',o:['You’re not as capable as you think.','You’re selfish.','You’re ordinary.','You’re difficult to love.','You don’t really know yourself.']},
{section:'Values',q:'When they genuinely conflict, which matters more?',o:['Truth','Harmony']},
{section:'Values',q:'Which would you sacrifice last?',o:['Family','Autonomy','Purpose','Adventure']},
{section:'Relationships',q:'Someone you’re beginning to care about becomes noticeably quieter for three days. Your first instinct?',o:['Assume they’re busy unless given reason otherwise.','Wonder whether their feelings changed.','Pull back too.','Ask directly what’s going on.','Notice it, but continue normally.']},
{section:'Relationships',q:'A great relationship should feel most like…',o:['Two highly independent lives choosing to intersect.','Two lives gradually becoming one shared life.','Deep interdependence without loss of individuality.']},
{section:'Under pressure',q:'Something important fails and you were responsible. What is your first mental move?',o:['Analyze exactly what went wrong.','Feel it intensely before I can think clearly.','Immediately start fixing it.','Consider what other people contributed.','Want to disappear for a while.']},
{section:'Under pressure',q:'When you feel emotionally exposed, which version of you is most likely to appear?',o:['Colder.','Funnier.','More agreeable.','More argumentative.','More analytical.']},
{section:'Contradiction',q:'The thing I least like needing from other people is…',o:['Approval','Help','Affection','Reassurance','Belonging','Nothing particularly bothers me about needing others']},
{section:'Contradiction',q:'Which possibility would be most unsettling if Wonder eventually concluded it was true?',o:['I need people more than I believe I do.','I care more about status or admiration than I admit.','I use independence to avoid vulnerability.','I sometimes mistake control for competence.','I compromise myself to avoid losing people.','I intellectualize feelings instead of experiencing them.','I am less self-aware than I think.']}
];
let qi=0;const answers={};const mount=document.getElementById('questionMount'),bar=document.getElementById('progressBar'),sectionLabel=document.getElementById('sectionLabel'),next=document.getElementById('nextQuestion'),prev=document.getElementById('prevQuestion');function renderQ(){const item=questions[qi];sectionLabel.textContent=item.section;bar.style.width=((qi+1)/questions.length*100)+'%';mount.innerHTML=`<div class="question-title">${item.q}</div><div class="options">${item.o.map((x,i)=>`<button class="option ${answers[qi]===i?'selected':''}" data-i="${i}">${x}</button>`).join('')}</div>`;mount.querySelectorAll('.option').forEach(el=>el.addEventListener('click',()=>{answers[qi]=Number(el.dataset.i);renderQ()}));prev.style.visibility=qi===0?'hidden':'visible';next.textContent=qi===questions.length-1?'See my Mirror':'Continue'}next.addEventListener('click',()=>{if(answers[qi]===undefined)return;if(qi<questions.length-1){qi++;renderQ()}else runProcessing()});prev.addEventListener('click',()=>{if(qi>0){qi--;renderQ()}else show('birth')});renderQ();
function runProcessing(){show('processing');const lines=['Separating what you say about yourself from what your choices suggest.','Looking at what you protect when certainty disappears.','Comparing your priorities when important values compete.','Finding the places where your conscious identity and instincts diverge.'];let i=0;const el=document.getElementById('processingLine');const timer=setInterval(()=>{i++;if(i<lines.length){el.textContent=lines[i]}else{clearInterval(timer);setTimeout(()=>show('mirror'),650)}},850)}
const rating=document.getElementById('rating');for(let i=1;i<=7;i++){const b=document.createElement('button');b.className='rate';b.textContent=i;b.addEventListener('click',()=>{document.querySelectorAll('.rate').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('wonder_mirror_accuracy',String(i))});rating.appendChild(b)}
document.querySelector('[data-next="home"]').addEventListener('click',()=>{localStorage.setItem('wonder_correction',document.getElementById('correction').value||'')});document.getElementById('saveJournal').addEventListener('click',()=>{const v=document.getElementById('journalEntry').value.trim();if(v){const entries=JSON.parse(localStorage.getItem('wonder_journal')||'[]');entries.unshift({text:v,createdAt:new Date().toISOString()});localStorage.setItem('wonder_journal',JSON.stringify(entries));document.getElementById('journalEntry').value='';alert('Saved privately in this preview.')} });document.getElementById('sendChat').addEventListener('click',()=>{const input=document.getElementById('chatInput');const v=input.value.trim();if(!v)return;const bubble=document.createElement('div');bubble.className='bubble user';bubble.textContent=v;document.querySelector('.chat').insertBefore(bubble,document.querySelector('.chat-input'));input.value=''});
show('welcome');