const $=id=>document.getElementById(id);
const screens=[...document.querySelectorAll('.screen')];
const state=JSON.parse(localStorage.getItem('wonder_preview_state')||'{}');
const save=()=>localStorage.setItem('wonder_preview_state',JSON.stringify(state));
const labels={welcome:'Private preview',birth:'Origin',assessment:'Assessment',processing:'Mirror',mirror:'Mirror',home:'Wonder',journal:'Journal',ai:'Wonder AI',matches:'Introductions'};
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));$('phaseLabel').textContent=labels[id]||'Wonder';state.screen=id;save();window.scrollTo({top:0,behavior:'smooth'});if(id==='journal')renderJournal();if(id==='matches')renderMatches();if(id==='ai')renderAI();}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.next)));
document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));

const Q=(section,q,o,keys)=>({section,q,o,keys});
const questions=[
Q('Instinct','You unexpectedly get three days entirely to yourself. Which sounds most appealing?',['Gather people and see where the weekend goes.','Disappear into something I’m fascinated by.','Plan a trip or do something I’ve never done.','Catch up, organize my life, and enjoy the quiet.'],[['social','novelty'],['abstraction','autonomy'],['novelty','openness'],['order','security']]),
Q('Instinct','You enter a dinner where you know almost no one.',['I usually start conversations myself.','I observe first, then approach whoever interests me.','I wait until someone draws me in.','I’m content speaking deeply with one person.'],[['social','assertive'],['abstraction','autonomy'],['trust'],['intimacy','depth']]),
Q('Instinct','Which would bother you more?',['Knowing exactly what the next five years look like.','Having almost no idea what the next five years look like.'],[['novelty','ambiguity'],['security','order']]),
Q('Instinct','When faced with a major decision and incomplete information, what do you do first?',['Make the best call available and adjust later.','Keep gathering information until uncertainty drops.','Follow what feels right even if I cannot fully explain it.','Construct the possibilities and compare outcomes.'],[['decisive','ambiguity'],['security','system'],['intuition','emotion'],['system','abstraction']]),
Q('Instinct','Someone intelligent strongly challenges something you believe. What happens first?',['I become curious about what they see that I don’t.','I immediately test their argument for weaknesses.','I defend my position until they demonstrate I’m wrong.','I dislike the conflict more than I care about winning it.'],[['flexibility','openness'],['system','direct'],['assertive','direct'],['appease','belonging']]),
Q('Instinct','Which sounds more like you?',['I naturally reduce complicated things into systems.','I naturally notice nuances that resist being reduced.'],[['system','order'],['abstraction','openness']]),
Q('Self','Which word would people who know you well be most likely to use?',['Strong-willed.','Warm.','Interesting.','Reliable.'],[['assertive'],['belonging','intimacy'],['openness','novelty'],['order','security']]),
Q('Self','Which would you most want someone you love to say about you?',['You make me feel safe.','You make my life larger.','You understand me completely.','I admire who you are.'],[['security','care'],['novelty','openness'],['intimacy','recognition'],['recognition','achievement']]),
Q('Self','Which compliment lands deepest?',['You’re brilliant.','You’re beautiful.','You’re a genuinely good person.','You’re unlike anyone I’ve met.','You’ve accomplished something remarkable.'],[['abstraction','recognition'],['recognition'],['meaning','belonging'],['openness','autonomy'],['achievement','status']]),
Q('Self','Which criticism would be hardest to hear from someone whose judgment you respect?',['You’re not as capable as you think.','You’re selfish.','You’re ordinary.','You’re difficult to love.','You don’t really know yourself.'],[['achievement'],['belonging'],['status','recognition'],['intimacy','reassurance'],['flexibility','shadow']]),
Q('Self','How true is this: I would rather solve my own problem than depend on someone else.',['Not very true.','Somewhat true.','Very true.'],[['interdependence'],['autonomy'],['autonomy','withdraw']]),
Q('Self','When I’m deeply upset, people usually…',['Know immediately.','Know something is wrong but not what.','Usually have no idea.','Only know if I deliberately tell them.'],[['expression','vulnerability'],['emotion'],['withdraw'],['control','privacy']]),
Q('Values','When they genuinely conflict, which matters more?',['Freedom','Security'],[['freedom','autonomy'],['security']]),
Q('Values','When they genuinely conflict, which matters more?',['Truth','Harmony'],[['truth','direct'],['harmony','appease']]),
Q('Values','Which life feels more tragic?',['Extraordinary achievement without deep love.','Deep love without extraordinary achievement.'],[['intimacy','love'],['achievement']]),
Q('Values','Which would you sacrifice last?',['Family','Autonomy','Purpose','Adventure'],[['family'],['autonomy'],['meaning'],['novelty']]),
Q('Values','Choose the one that pulls you most.',['Beauty','Knowledge','Wealth','Service','Influence'],[['beauty'],['knowledge'],['wealth'],['service'],['influence']]),
Q('Values','Which would disturb you more?',['Being successful at something meaningless.','Devoting yourself to something meaningful and failing publicly.'],[['meaning'],['achievement','status']]),
Q('Values','You have enough money never to work again. Which impulse survives strongest?',['Make things.','Learn things.','Experience things.','Build something important.','Care for people I love.'],[['creativity'],['knowledge'],['novelty'],['achievement','influence'],['family','intimacy']]),
Q('Values','Which betrayal would be hardest to forgive?',['Dishonesty','Disloyalty','Abandonment','Public humiliation','Being controlled'],[['truth'],['loyalty'],['reassurance','intimacy'],['status','recognition'],['autonomy','freedom']]),
Q('Relationships','Someone you’re beginning to care about becomes noticeably quieter for three days. Your first instinct?',['Assume they’re busy unless given reason otherwise.','Wonder whether their feelings changed.','Pull back too.','Ask directly what’s going on.','Notice it, but continue normally.'],[['trust'],['reassurance','emotion'],['withdraw','autonomy'],['direct','vulnerability'],['trust','autonomy']]),
Q('Relationships','A partner begins relying on you much more emotionally.',['I usually feel closer to them.','I care, but eventually feel crowded.','It depends whether the dependence feels reciprocal.','I become uncomfortable surprisingly quickly.'],[['intimacy'],['autonomy'],['reciprocity'],['withdraw','autonomy']]),
Q('Relationships','During serious conflict, which impulse appears first?',['Solve the problem.','Make sure the relationship is okay.','Get away until I can think.','Make them understand my position.','Understand why this happened.'],[['system','direct'],['appease','reassurance'],['withdraw','analysis'],['assertive','control'],['flexibility','abstraction']]),
Q('Relationships','What must love contain?',['Passion','Peace','Admiration','Friendship','Growth','Loyalty'],[['passion'],['harmony'],['recognition'],['belonging'],['growth'],['loyalty']]),
Q('Relationships','Someone asks something deeply personal earlier than you expected.',['I answer honestly if I trust their intent.','I answer partly and keep the rest mine.','I redirect.','I might answer more than I intended.'],[['vulnerability','trust'],['privacy','control'],['withdraw'],['vulnerability','expression']]),
Q('Relationships','Which sounds closest?',['Once someone chooses me, I rarely question it.','I occasionally need confirmation.','Changes in someone’s behavior can make me question things quickly.','I dislike needing reassurance enough that I usually won’t ask for it.'],[['trust'],['reassurance'],['reassurance','emotion'],['reassurance','autonomy','withdraw']]),
Q('Relationships','You realize you’ve initiated almost every plan with someone for a month.',['I’d probably stop initiating.','I’d ask them about it.','I’d continue if I enjoy seeing them.','I’d feel hurt before I did anything.'],[['reciprocity','withdraw'],['direct','reciprocity'],['autonomy'],['emotion','reassurance']]),
Q('Relationships','A great relationship should feel most like…',['Two highly independent lives choosing to intersect.','Two lives gradually becoming one shared life.','Deep interdependence without loss of individuality.'],[['autonomy'],['intimacy','belonging'],['intimacy','autonomy']]),
Q('Under pressure','Something important fails and you were responsible. What is your first mental move?',['Analyze exactly what went wrong.','Feel it intensely before I can think clearly.','Immediately start fixing it.','Consider what other people contributed.','Want to disappear for a while.'],[['analysis','system'],['emotion'],['control','decisive'],['externalize'],['withdraw']]),
Q('Under pressure','When life becomes chaotic, I tend to become…',['More organized.','More controlling.','More avoidant.','More emotional.','More accommodating toward everyone.'],[['order'],['control'],['withdraw'],['emotion','expression'],['appease']]),
Q('Under pressure','Someone close to you forms an unfair interpretation of your motives.',['I need to correct it.','I explain once and let them decide.','It hurts more than I like admitting.','I become angry that they could think that of me.','I detach.'],[['control','recognition'],['autonomy'],['emotion','recognition'],['assertive','externalize'],['withdraw']]),
Q('Under pressure','When you feel emotionally exposed, which version of you is most likely to appear?',['Colder.','Funnier.','More agreeable.','More argumentative.','More analytical.'],[['withdraw'],['appease','deflect'],['appease'],['direct','control'],['analysis']]),
Q('Shadow','The thing I least like needing from other people is…',['Approval','Help','Affection','Reassurance','Belonging','Nothing particularly bothers me about needing others'],[['recognition','shadow'],['autonomy','shadow'],['intimacy','shadow'],['reassurance','shadow'],['belonging','shadow'],['trust']]),
Q('Shadow','Which characteristic in other people irritates you most?',['Neediness','Arrogance','Weakness','Selfishness','Attention-seeking','Rigidity','Indecisiveness','Emotional coldness','Naivety','Conformity'],[['autonomy'],['status'],['achievement'],['reciprocity'],['recognition'],['control'],['decisive'],['intimacy'],['system'],['openness']]),
Q('Contradiction','Which statement is most true?',['Most people understand me reasonably well.','People know different versions of me.','Very few people know me deeply.','I’m not sure anyone fully knows me.'],[['trust'],['persona'],['intimacy','privacy'],['recognition','persona']]),
Q('Contradiction','Which possibility would be most unsettling if Wonder eventually concluded it was true?',['I need people more than I believe I do.','I care more about status or admiration than I admit.','I use independence to avoid vulnerability.','I sometimes mistake control for competence.','I compromise myself to avoid losing people.','I intellectualize feelings instead of experiencing them.','I am less self-aware than I think.'],[['reassurance','shadow'],['status','shadow'],['autonomy','withdraw','shadow'],['control','shadow'],['appease','shadow'],['analysis','shadow'],['flexibility','shadow']])
];

let qi=Number(state.qi||0);state.answers=state.answers||{};
const answers=state.answers;
function renderQ(){const item=questions[qi];$('sectionLabel').textContent=item.section;$('progressBar').style.width=((qi+1)/questions.length*100)+'%';$('questionMount').innerHTML=`<div class="question-title">${item.q}</div><div class="options">${item.o.map((x,i)=>`<button class="option ${answers[qi]===i?'selected':''}" data-i="${i}">${x}</button>`).join('')}</div>`;$('questionMount').querySelectorAll('.option').forEach(el=>el.onclick=()=>{answers[qi]=Number(el.dataset.i);save();renderQ()});$('prevQuestion').style.visibility=qi===0?'hidden':'visible';$('nextQuestion').textContent=qi===questions.length-1?'See my Mirror':'Continue';}
$('nextQuestion').onclick=()=>{if(answers[qi]===undefined)return;if(qi<questions.length-1){qi++;state.qi=qi;save();renderQ()}else{state.completedAssessment=true;save();runProcessing()}};
$('prevQuestion').onclick=()=>{if(qi>0){qi--;state.qi=qi;save();renderQ()}else show('birth')};

function addScore(scores,key,w=1){scores[key]=(scores[key]||0)+w}
function scorePreview(){const scores={};questions.forEach((q,i)=>{const ai=answers[i];if(ai===undefined)return;(q.keys[ai]||[]).forEach(k=>addScore(scores,k));});return scores}
const archetypes={
Architect:{keys:['system','order','achievement','decisive','autonomy'],move:['You build coherence.','You tend to organize complexity into systems, decisions, and direction.'],drive:['Mastery before approval.','Competence and autonomy appear to matter more to you than fitting neatly into other people’s expectations.']},
Seer:{keys:['abstraction','openness','intuition','knowledge','meaning'],move:['You notice patterns before they become obvious.','Your attention naturally moves toward underlying meaning, possibility, and connections between things.'],drive:['Understanding before certainty.','You appear motivated by insight, originality, and the feeling that there is something deeper to discover.']},
Explorer:{keys:['novelty','freedom','openness','autonomy','growth'],move:['You move toward possibility.','You come alive around novelty, movement, and experiences that make your world larger.'],drive:['Freedom before predictability.','You seem willing to trade some security for aliveness, discovery, and self-direction.']},
Sovereign:{keys:['assertive','influence','status','achievement','control'],move:['You naturally take the wheel.','You tend to create direction rather than wait for it, especially when stakes are high.'],drive:['Agency before permission.','Achievement, influence, and the ability to shape outcomes appear unusually important to you.']},
Alchemist:{keys:['meaning','emotion','growth','intimacy','creativity'],move:['You transform experience into meaning.','You tend to metabolize life through depth, emotion, symbolism, and personal transformation.'],drive:['Depth before simplicity.','You seem drawn toward experiences and people that change you rather than merely reassure you.']},
Devotee:{keys:['intimacy','loyalty','family','belonging','reassurance'],move:['You orient through relationship.','Connection, loyalty, and emotional significance seem to organize more of your inner life than you may always advertise.'],drive:['Bond before distance.','Being chosen, known, and emotionally connected appears to carry real psychological weight for you.']},
Guardian:{keys:['security','order','family','loyalty','care'],move:['You stabilize what matters.','You tend to create safety through reliability, structure, and protecting the people or commitments you value.'],drive:['Continuity before chaos.','Trust, responsibility, and the ability to depend on what matters appear central to you.']},
Maverick:{keys:['autonomy','freedom','openness','direct','novelty'],move:['You resist being absorbed by the expected.','You tend to preserve independence even when conformity would make life easier.'],drive:['Authenticity before approval.','Self-direction and the right to define your own terms appear central to your identity.']}
};
function archetypeResult(){const scores=scorePreview();let best='Architect',bestScore=-1;Object.entries(archetypes).forEach(([name,a])=>{const s=a.keys.reduce((n,k)=>n+(scores[k]||0),0);if(s>bestScore){best=name;bestScore=s}});return {name:best,scores}}
function buildMirror(){const {name,scores}=archetypeResult();const a=archetypes[name];state.archetype=name;save();$('archetypeName').textContent='The '+name;$('archetypeNote').textContent='Primary archetype · preview model';$('mirrorMoveTitle').textContent=a.move[0];$('mirrorMove').textContent=a.move[1];$('mirrorDriveTitle').textContent=a.drive[0];$('mirrorDrive').textContent=a.drive[1];
const intimate=(scores.intimacy||0)+(scores.reassurance||0), autonomous=(scores.autonomy||0)+(scores.withdraw||0), emotional=(scores.emotion||0)+(scores.expression||0), analytical=(scores.analysis||0)+(scores.system||0);
if(intimate>autonomous){$('mirrorRelTitle').textContent='Closeness carries weight.';$('mirrorRel').textContent='You appear to invest deeply once a bond matters. Reciprocity and emotional consistency are likely to affect you more than casual chemistry alone.'}else{$('mirrorRelTitle').textContent='Depth without engulfment.';$('mirrorRel').textContent='You seem drawn to substantial connection, but closeness works best when it does not require surrendering your individuality.'}
if(autonomous>intimate && (scores.reassurance||0)>1){$('mirrorShadowTitle').textContent='Independence may be part value, part armor.';$('mirrorShadow').textContent='You may identify strongly with self-sufficiency while still caring deeply about being chosen and understood. Wonder would want more evidence before treating that as settled.'}else if((scores.control||0)>2){$('mirrorShadowTitle').textContent='Competence and control may blur under pressure.';$('mirrorShadow').textContent='When uncertainty rises, taking charge may genuinely help you. It may also sometimes protect you from having to remain inside uncertainty long enough to feel it.'}else if((scores.appease||0)>2){$('mirrorShadowTitle').textContent='Harmony may sometimes cost you information about yourself.';$('mirrorShadow').textContent='Your instinct to preserve connection may occasionally make it harder to notice what you actually want until later.'}else{$('mirrorShadowTitle').textContent='Your strongest trait may also have an opposite.';$('mirrorShadow').textContent='Wonder sees some tension between the identity you consciously prefer and what appears when the stakes become emotional. It needs more longitudinal evidence.'}
$('mirrorUncertain').textContent=analytical>emotional?'Whether your instinct to analyze emotion helps you metabolize it, or sometimes keeps you one step removed from experiencing it.':'Whether emotional immediacy helps you access truth quickly, or sometimes makes uncertainty feel more meaningful than it is.';
$('homeArchetypeLine').textContent=`Your current center is The ${name}. Wonder gets more precise as you reflect, write, and interact with it.`;state.scores=scores;save();}

function runProcessing(){show('processing');const lines=['Separating what you say about yourself from what your choices suggest.','Looking at what you protect when certainty disappears.','Comparing your priorities when important values compete.','Finding the places where your conscious identity and instincts diverge.'];let i=0;$('processingLine').textContent=lines[0];const timer=setInterval(()=>{i++;if(i<lines.length){$('processingLine').textContent=lines[i]}else{clearInterval(timer);buildMirror();setTimeout(()=>show('mirror'),500)}},650)}
for(let i=1;i<=7;i++){const b=document.createElement('button');b.className='rate';b.textContent=i;if(Number(state.accuracy)===i)b.classList.add('selected');b.onclick=()=>{state.accuracy=i;save();document.querySelectorAll('.rate').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};$('rating').appendChild(b)}
$('saveMirror').onclick=()=>{state.correction=$('correction').value.trim();save();show('home')};

$('birthContinue').onclick=()=>{state.birth={dob:$('dob').value,tob:$('tob').value,pob:$('pob').value.trim(),toa:$('toa').value};save();show('assessment');renderQ()};
function hydrateBirth(){if(state.birth){$('dob').value=state.birth.dob||'';$('tob').value=state.birth.tob||'';$('pob').value=state.birth.pob||'';$('toa').value=state.birth.toa||'Exact'}}

function renderJournal(){const entries=state.journal||[];$('journalHistory').innerHTML=entries.length?`<div class="eyebrow" style="margin-top:34px">Recent entries</div>`+entries.slice(0,5).map(e=>`<article class="uncertain"><span>${new Date(e.createdAt).toLocaleDateString()}</span><p>${e.text.replace(/[<>]/g,'')}</p></article>`).join(''):''}
$('saveJournal').onclick=()=>{const v=$('journalEntry').value.trim();if(!v)return;state.journal=state.journal||[];state.journal.unshift({text:v,createdAt:new Date().toISOString()});save();$('journalEntry').value='';renderJournal()};

function aiPrompt(){const n=state.archetype||archetypeResult().name;if(n==='Architect'||n==='Sovereign')return 'You appear to value agency and competence strongly. What happens inside you when you cannot fix, influence, or understand something important?';if(n==='Devotee'||n==='Guardian')return 'Connection seems to matter deeply to you. How do you know when care becomes over-accommodation?';if(n==='Explorer'||n==='Maverick')return 'Freedom appears central to you. What kind of closeness feels expansive rather than constraining?';return 'You seem drawn toward depth and meaning. How do you distinguish a real pattern from one you may be creating because you want an experience to mean something?'}
function renderAI(){if(!$('wonderPrompt').textContent)$('wonderPrompt').textContent=aiPrompt()}
$('sendChat').onclick=()=>{const v=$('chatInput').value.trim();if(!v)return;const user=document.createElement('div');user.className='bubble user';user.textContent=v;$('chat').insertBefore(user,$('chat').querySelector('.chat-input'));state.chat=state.chat||[];state.chat.push({role:'user',text:v});const response=document.createElement('div');response.className='bubble wonder';const low=v.toLowerCase();response.textContent=low.includes('wrong')||low.includes('false')?'That matters. I would lower confidence in that interpretation rather than forcing your answer to fit it. What feels more accurate instead?':low.includes('yes')||low.includes('true')?'Then the useful question is not whether the pattern exists, but when it appears and what it protects. When do you notice it most strongly?':'I’m treating that as new evidence, not a conclusion. What would someone who knows you extremely well say about this?';$('chat').insertBefore(response,$('chat').querySelector('.chat-input'));state.chat.push({role:'wonder',text:response.textContent});save();$('chatInput').value=''};

const profiles=[
{name:'Julian',age:29,arch:'Seer',cls:'p1',text:'Film, systems thinking, long walks, questions with no obvious answer.',why:{Architect:'intellectual intensity, autonomy, complementary emotional expression',Seer:'shared abstraction with enough difference to avoid mirroring',Explorer:'curiosity and cognitive depth without requiring identical tempo',Sovereign:'independent thinking that is unlikely to collapse into admiration',Alchemist:'shared appetite for meaning with a more analytic center',Devotee:'depth and steadiness with a less fusion-oriented style',Guardian:'curiosity that may expand routine without threatening stability',Maverick:'independence and nonconformity with intellectual ballast'}},
{name:'Amelia',age:27,arch:'Alchemist',cls:'p2',text:'Design, philosophy, ritual, museums, improbable dinner conversations.',why:{Architect:'shared meaning orientation, aesthetic sensitivity, constructive difference in temperament',Seer:'symbolic depth and emotional texture complement abstraction',Explorer:'novelty with enough emotional depth to make experience matter',Sovereign:'soft power and depth may counterbalance drive',Alchemist:'high resonance in meaning, aesthetics, and transformation',Devotee:'emotional depth and relational significance',Guardian:'warmth and meaning may widen the emotional palette',Maverick:'originality without demanding sameness'}},
{name:'Adrian',age:31,arch:'Sovereign',cls:'p3',text:'Building companies, architecture, travel, disciplined curiosity.',why:{Architect:'matched agency, compatible ambition, potential friction around control',Seer:'execution may ground abstraction while preserving intellectual respect',Explorer:'high agency and movement with enough structure to create momentum',Sovereign:'matched ambition with meaningful power-friction to evaluate',Alchemist:'stability and agency may complement depth',Devotee:'clarity and decisiveness may feel secure if emotionally available',Guardian:'shared responsibility and long-horizon orientation',Maverick:'strong autonomy on both sides; attraction may depend on mutual respect'}}
];
function renderMatches(){const a=state.archetype||archetypeResult().name;$('matchGrid').innerHTML=profiles.map(p=>`<article class="match"><div class="portrait ${p.cls}"></div><span>The ${p.arch}</span><h3>${p.name}, ${p.age}</h3><p>${p.text}</p><small>Why Wonder chose this: ${p.why[a]||p.why.Architect}.</small><button class="ghost interest" data-name="${p.name}" style="margin-top:16px">I’m curious</button></article>`).join('');document.querySelectorAll('.interest').forEach(b=>b.onclick=()=>{state.interests=state.interests||[];if(!state.interests.includes(b.dataset.name))state.interests.push(b.dataset.name);save();b.textContent='Saved to explore';b.disabled=true})}

hydrateBirth();renderQ();if(state.completedAssessment)buildMirror();if(state.screen&&state.screen!=='processing'){$('resumeBtn').style.display='inline-flex';$('resumeBtn').onclick=()=>show(state.screen)}show('welcome');