import * as THREE from 'https://esm.sh/three@0.184.0';
import {OrbitControls} from 'https://esm.sh/three@0.184.0/examples/jsm/controls/OrbitControls.js';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://ernpiurftcjkvnicogsp.supabase.co';
const SUPABASE_KEY='sb_publishable_0_3gRd3YQeyc8rmA_SH1pA_Xmd6gjjV';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const authGate=$('authGate'),app=$('app'),authForm=$('authForm'),authError=$('authError');
let regions=[],sources=[],knowledge=[],links=[],selected=null,scene,camera,renderer,controls,raycaster,pointer,brainGroup,meshes=[],lineGroup,mode='anatomy';

async function isAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return false;const {data,error}=await supabase.from('wonder_admins').select('role').eq('user_id',user.id).maybeSingle();return !error&&!!data;}
async function boot(){if(await isAdmin()){authGate.classList.add('hidden');app.classList.remove('hidden');await loadMind();init3D();renderRegionList();selectRegion(regions.find(r=>r.region_number===14)||regions[0]);}else{await supabase.auth.signOut();authGate.classList.remove('hidden');app.classList.add('hidden');}}
authForm.addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';const {error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){authError.textContent='Unable to authenticate.';return}if(!(await isAdmin())){await supabase.auth.signOut();authError.textContent='This account is not authorized for Wonder Mind.';return}boot();});
$('signOut').onclick=async()=>{await supabase.auth.signOut();location.reload()};

async function loadMind(){const [r,s,k,l]=await Promise.all([supabase.from('wonder_mind_regions').select('*').eq('is_active',true).order('region_number'),supabase.from('wonder_mind_sources').select('*').order('credibility_score',{ascending:false}),supabase.from('wonder_mind_knowledge').select('*').eq('status','active'),supabase.from('wonder_mind_links').select('*')]);if(r.error)throw r.error;regions=r.data||[];sources=s.data||[];knowledge=k.data||[];links=l.data||[];$('systemStatus').textContent=`${regions.length} regions online`;$('counts').textContent=`${sources.length} SOURCES · ${knowledge.length} KNOWLEDGE NODES · ${links.length} SYNAPTIC LINKS`;}

function renderRegionList(){const root=$('regionList');root.innerHTML='';regions.forEach(r=>{const b=document.createElement('button');b.className='region-btn';b.dataset.id=r.id;b.innerHTML=`<span class="num">${String(r.region_number).padStart(2,'0')}</span><span>${escapeHtml(r.short_name)}</span><span class="tier">${escapeHtml(r.evidence_floor)}</span>`;b.onclick=()=>selectRegion(r);root.appendChild(b)});}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function chips(arr=[]){return `<div class="chips">${(arr||[]).map(x=>`<span class="chip">${escapeHtml(x)}</span>`).join('')}</div>`}
function selectRegion(r){if(!r)return;selected=r;document.querySelectorAll('.region-btn').forEach(x=>x.classList.toggle('active',x.dataset.id===r.id));meshes.forEach(m=>{const active=m.userData.region.id===r.id;m.material.emissiveIntensity=active?1.35:.32;m.scale.setScalar(active?1.17:1)});const ks=knowledge.filter(k=>k.region_id===r.id);const sourceIds=new Set(ks.map(k=>k.source_id).filter(Boolean));const direct=sources.filter(s=>sourceIds.has(s.id)||((r.knowledge_base||[]).some(n=>n.toLowerCase().includes((s.creator||'').split(',')[0].toLowerCase())||s.title.toLowerCase().includes(n.toLowerCase()))));const incoming=links.filter(l=>l.to_region_id===r.id).length,outgoing=links.filter(l=>l.from_region_id===r.id).length;$('inspector').innerHTML=`<div class="region-head"><span class="number">REGION ${String(r.region_number).padStart(2,'0')}</span><h2>${escapeHtml(r.name)}</h2><div class="question">${escapeHtml(r.core_question)}</div><p class="purpose">${escapeHtml(r.purpose)}</p></div><div class="metrics"><div class="metric"><b>${Math.round(Number(r.match_weight)*100)}</b><span>MATCH WEIGHT</span></div><div class="metric"><b>${Math.round(Number(r.guide_weight)*100)}</b><span>GUIDE WEIGHT</span></div><div class="metric"><b>${incoming+outgoing}</b><span>CONNECTIONS</span></div></div><div class="section"><h3>Reasons over</h3>${chips(r.reasons_over)}</div><div class="section"><h3>Outputs</h3>${chips(r.outputs)}</div><div class="section"><h3>Knowledge base</h3>${chips(r.knowledge_base)}</div><div class="section"><h3>Guardrail</h3><div class="guardrail">${escapeHtml(r.guardrail)}</div></div><div class="section"><h3>Operational knowledge · ${ks.length}</h3>${ks.length?ks.map(k=>`<div class="knowledge-card"><b>${escapeHtml(k.title)}</b><div class="meta"><span>${escapeHtml(k.evidence_grade)}</span><span>${Math.round(Number(k.confidence)*100)}% confidence</span><span>${escapeHtml(k.kind)}</span></div><p>${escapeHtml(k.claim)}</p><p><strong>Application:</strong> ${escapeHtml(k.application)}</p>${k.counterevidence?`<p><strong>Counterevidence:</strong> ${escapeHtml(k.counterevidence)}</p>`:''}</div>`).join(''):'<p class="purpose">No operational nodes yet. This region is scaffolded for expansion.</p>'}</div><div class="section"><h3>Sources · ${direct.length}</h3>${direct.slice(0,12).map(s=>`<div class="source-card"><b>${escapeHtml(s.title)}</b><div class="meta"><span>${escapeHtml(s.evidence_tier)}</span><span>${s.credibility_score?Number(s.credibility_score).toFixed(1)+'/10':''}</span><span>${escapeHtml(s.epistemic_role)}</span></div><p>${escapeHtml(s.summary)}</p></div>`).join('')}</div>`;focusRegion(r);}

function init3D(){const canvas=$('brain');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(0,0,8.7);renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=13;controls.autoRotate=true;controls.autoRotateSpeed=.22;controls.target.set(0,.05,0);scene.add(new THREE.AmbientLight(0xcbbd9d,1.25));const key=new THREE.PointLight(0xe8d5a5,25,20);key.position.set(3,4,5);scene.add(key);const rim=new THREE.PointLight(0x7f6848,18,18);rim.position.set(-4,-2,-4);scene.add(rim);brainGroup=new THREE.Group();lineGroup=new THREE.Group();scene.add(brainGroup,lineGroup);buildBrain();raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();canvas.addEventListener('pointerdown',onPick);window.addEventListener('resize',resize);$('resetView').onclick=()=>{camera.position.set(0,0,8.7);controls.target.set(0,.05,0)};document.querySelectorAll('.mode-tabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode-tabs button').forEach(x=>x.classList.toggle('active',x===b));lineGroup.visible=mode==='network';$('stageTitle').textContent=mode==='network'?'Synaptic network':'Cognitive anatomy';});resize();animate();}
function brainShape(x,y,z){const lobe=Math.exp(-((x*x)/5.5+(y*y)/3.5+(z*z)/3.3));return 1+.08*Math.sin(x*3+y*2)+.05*Math.cos(z*4)+.12*lobe}
function buildBrain(){const palette=[0xc2aa7c,0x9f8968,0xbaa17b,0x8f7c65,0xc6b58d,0xa58b74,0xd0b87e,0x8d826e,0xaaa18a,0xc4a66c,0x83745e,0xd5c38f,0x9c705f,0xc7b178,0x7e755f,0xb39873,0x8b8068];regions.forEach((r,i)=>{const p=new THREE.Vector3(Number(r.x),Number(r.y),Number(r.z));const scale=brainShape(p.x,p.y,p.z);const geo=new THREE.IcosahedronGeometry(.57*scale,3);const pos=geo.attributes.position;for(let j=0;j<pos.count;j++){const v=new THREE.Vector3().fromBufferAttribute(pos,j);const n=.035*Math.sin(v.x*13+i)+.025*Math.cos(v.y*17-i)+.018*Math.sin(v.z*19);v.multiplyScalar(1+n);pos.setXYZ(j,v.x,v.y,v.z)}geo.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({color:palette[i%palette.length],roughness:.72,metalness:.06,transparent:true,opacity:.93,emissive:palette[i%palette.length],emissiveIntensity:.32});const mesh=new THREE.Mesh(geo,mat);mesh.position.copy(p);mesh.userData.region=r;brainGroup.add(mesh);meshes.push(mesh)});links.forEach(l=>{const a=regions.find(r=>r.id===l.from_region_id),b=regions.find(r=>r.id===l.to_region_id);if(!a||!b)return;const points=[new THREE.Vector3(Number(a.x),Number(a.y),Number(a.z)),new THREE.Vector3(Number(b.x),Number(b.y),Number(b.z))];const geo=new THREE.BufferGeometry().setFromPoints(points);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x9f8a62,transparent:true,opacity:.18+Number(l.weight)*.3}));lineGroup.add(line)});lineGroup.visible=false;}
function focusRegion(r){if(!controls||!camera)return;controls.autoRotate=false;const target=new THREE.Vector3(Number(r.x),Number(r.y),Number(r.z));controls.target.copy(target);const dir=camera.position.clone().sub(target).normalize();camera.position.copy(target.clone().add(dir.multiplyScalar(7.2)));}
function onPick(e){const rect=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-rect.left)/rect.width)*2-1;pointer.y=-((e.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes,false)[0];if(hit)selectRegion(hit.object.userData.region)}
function resize(){const el=$('brain').parentElement,w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}
boot().catch(e=>{console.error(e);authError.textContent='Wonder Mind could not initialize.'});