import * as THREE from 'https://esm.sh/three@0.184.0';
import {OrbitControls} from 'https://esm.sh/three@0.184.0/examples/jsm/controls/OrbitControls.js';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://ernpiurftcjkvnicogsp.supabase.co';
const SUPABASE_KEY='sb_publishable_0_3gRd3YQeyc8rmA_SH1pA_Xmd6gjjV';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const authGate=$('authGate'),app=$('app'),authForm=$('authForm'),authError=$('authError');
let regions=[],sources=[],knowledge=[],links=[],stateSnapshots=[],trajectories=[],glyphPrograms=[],glyphLexicon=[],selected=null,scene,camera,renderer,controls,raycaster,pointer,brainGroup,meshes=[],lineGroup,trajectoryGroup,mode='anatomy';

async function isAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return false;const {data,error}=await supabase.from('wonder_admins').select('role').eq('user_id',user.id).maybeSingle();return !error&&!!data;}
async function boot(){if(await isAdmin()){authGate.classList.add('hidden');app.classList.remove('hidden');await loadMind();init3D();renderRegionList();selectRegion(regions.find(r=>r.region_number===14)||regions[0]);}else{await supabase.auth.signOut();authGate.classList.remove('hidden');app.classList.add('hidden');}}
authForm.addEventListener('submit',async e=>{e.preventDefault();authError.textContent='';const {error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){authError.textContent='Unable to authenticate.';return}if(!(await isAdmin())){await supabase.auth.signOut();authError.textContent='This account is not authorized for Wonder Mind.';return}boot();});
$('signOut').onclick=async()=>{await supabase.auth.signOut();location.reload()};

async function loadMind(){const [r,s,k,l,ss,tr,gp,gl]=await Promise.all([supabase.from('wonder_mind_regions').select('*').eq('is_active',true).order('region_number'),supabase.from('wonder_mind_sources').select('*').order('credibility_score',{ascending:false}),supabase.from('wonder_mind_knowledge').select('*').eq('status','active'),supabase.from('wonder_mind_links').select('*'),supabase.from('wonder_mind_state_snapshots').select('id,user_id,run_id,entity_type,space_version,state_hash,projection,confidence,observed_at').order('observed_at',{ascending:false}).limit(80),supabase.from('wonder_mind_trajectories').select('*').order('created_at',{ascending:false}).limit(20),supabase.from('wonder_mind_glyph_programs').select('id,user_id,run_id,language_version,purpose,tokens,source_hash,reversible,created_at').order('created_at',{ascending:false}).limit(20),supabase.from('wonder_mind_glyph_lexicon').select('*').order('glyph_code')]);if(r.error)throw r.error;regions=r.data||[];sources=s.data||[];knowledge=k.data||[];links=l.data||[];stateSnapshots=ss.data||[];trajectories=tr.data||[];glyphPrograms=gp.data||[];glyphLexicon=gl.data||[];$('systemStatus').textContent=`${regions.length} regions online`;$('counts').textContent=`${sources.length} SOURCES · ${knowledge.length} KNOWLEDGE NODES · ${stateSnapshots.length} STATES · ${glyphPrograms.length} GLYPH PROGRAMS`;}

function renderRegionList(){const root=$('regionList');root.innerHTML='';regions.forEach(r=>{const b=document.createElement('button');b.className='region-btn';b.dataset.id=r.id;b.innerHTML=`<span class="num">${String(r.region_number).padStart(2,'0')}</span><span>${escapeHtml(r.short_name)}</span><span class="tier">${escapeHtml(r.evidence_floor)}</span>`;b.onclick=()=>selectRegion(r);root.appendChild(b)});}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function chips(arr=[]){return `<div class="chips">${(arr||[]).map(x=>`<span class="chip">${escapeHtml(x)}</span>`).join('')}</div>`}
function selectRegion(r){if(!r)return;selected=r;document.querySelectorAll('.region-btn').forEach(x=>x.classList.toggle('active',x.dataset.id===r.id));meshes.forEach(m=>{const active=m.userData.region.id===r.id;m.material.emissiveIntensity=active?1.35:.32;m.scale.setScalar(active?1.17:1)});const ks=knowledge.filter(k=>k.region_id===r.id);const sourceIds=new Set(ks.map(k=>k.source_id).filter(Boolean));const direct=sources.filter(s=>sourceIds.has(s.id)||((r.knowledge_base||[]).some(n=>n.toLowerCase().includes((s.creator||'').split(',')[0].toLowerCase())||s.title.toLowerCase().includes(n.toLowerCase()))));const incoming=links.filter(l=>l.to_region_id===r.id).length,outgoing=links.filter(l=>l.from_region_id===r.id).length;$('inspector').innerHTML=`<div class="region-head"><span class="number">REGION ${String(r.region_number).padStart(2,'0')}</span><h2>${escapeHtml(r.name)}</h2><div class="question">${escapeHtml(r.core_question)}</div><p class="purpose">${escapeHtml(r.purpose)}</p></div><div class="metrics"><div class="metric"><b>${Math.round(Number(r.match_weight)*100)}</b><span>MATCH WEIGHT</span></div><div class="metric"><b>${Math.round(Number(r.guide_weight)*100)}</b><span>GUIDE WEIGHT</span></div><div class="metric"><b>${incoming+outgoing}</b><span>CONNECTIONS</span></div></div><div class="section"><h3>Reasons over</h3>${chips(r.reasons_over)}</div><div class="section"><h3>Outputs</h3>${chips(r.outputs)}</div><div class="section"><h3>Knowledge base</h3>${chips(r.knowledge_base)}</div><div class="section"><h3>Guardrail</h3><div class="guardrail">${escapeHtml(r.guardrail)}</div></div><div class="section"><h3>Operational knowledge · ${ks.length}</h3>${ks.length?ks.map(k=>`<div class="knowledge-card"><b>${escapeHtml(k.title)}</b><div class="meta"><span>${escapeHtml(k.evidence_grade)}</span><span>${Math.round(Number(k.confidence)*100)}% confidence</span><span>${escapeHtml(k.kind)}</span></div><p>${escapeHtml(k.claim)}</p><p><strong>Application:</strong> ${escapeHtml(k.application)}</p>${k.counterevidence?`<p><strong>Counterevidence:</strong> ${escapeHtml(k.counterevidence)}</p>`:''}</div>`).join(''):'<p class="purpose">No operational nodes yet. This region is scaffolded for expansion.</p>'}</div><div class="section"><h3>Sources · ${direct.length}</h3>${direct.slice(0,12).map(s=>`<div class="source-card"><b>${escapeHtml(s.title)}</b><div class="meta"><span>${escapeHtml(s.evidence_tier)}</span><span>${s.credibility_score?Number(s.credibility_score).toFixed(1)+'/10':''}</span><span>${escapeHtml(s.epistemic_role)}</span></div><p>${escapeHtml(s.summary)}</p></div>`).join('')}</div>`;focusRegion(r);}

function init3D(){const canvas=$('brain');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(0,0,8.7);renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=13;controls.autoRotate=true;controls.autoRotateSpeed=.22;controls.target.set(0,.05,0);scene.add(new THREE.AmbientLight(0xcbbd9d,1.25));const key=new THREE.PointLight(0xe8d5a5,25,20);key.position.set(3,4,5);scene.add(key);const rim=new THREE.PointLight(0x7f6848,18,18);rim.position.set(-4,-2,-4);scene.add(rim);brainGroup=new THREE.Group();lineGroup=new THREE.Group();trajectoryGroup=new THREE.Group();scene.add(brainGroup,lineGroup,trajectoryGroup);buildBrain();buildTrajectories();raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();canvas.addEventListener('pointerdown',onPick);window.addEventListener('resize',resize);$('resetView').onclick=()=>{camera.position.set(0,0,8.7);controls.target.set(0,.05,0)};document.querySelectorAll('.mode-tabs button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode,b));resize();animate();}

function setMode(next,button){mode=next;document.querySelectorAll('.mode-tabs button').forEach(x=>x.classList.toggle('active',x===button));brainGroup.visible=mode==='anatomy'||mode==='network';lineGroup.visible=mode==='network';trajectoryGroup.visible=mode==='trajectory';$('glyphOverlay').classList.toggle('hidden',mode!=='glyphs');$('brain').style.opacity=mode==='glyphs'?'.12':'1';if(mode==='network'){$('stageTitle').textContent='Synaptic network';$('stageSub').textContent='Functional links between cognitive regions';}else if(mode==='trajectory'){$('stageTitle').textContent='State trajectory';$('stageSub').textContent='3D projection · time remains explicit · uncertainty retained';renderTrajectoryInspector();}else if(mode==='glyphs'){$('stageTitle').textContent='Wonder Glyph Language';$('stageSub').textContent='Reversible symbolic intermediate representation';renderGlyphMode();}else{$('stageTitle').textContent='Cognitive anatomy';$('stageSub').textContent='Drag to rotate · scroll to zoom · select a region';if(selected)selectRegion(selected);}}
function brainShape(x,y,z){const lobe=Math.exp(-((x*x)/5.5+(y*y)/3.5+(z*z)/3.3));return 1+.08*Math.sin(x*3+y*2)+.05*Math.cos(z*4)+.12*lobe}
function buildBrain(){const palette=[0xc2aa7c,0x9f8968,0xbaa17b,0x8f7c65,0xc6b58d,0xa58b74,0xd0b87e,0x8d826e,0xaaa18a,0xc4a66c,0x83745e,0xd5c38f,0x9c705f,0xc7b178,0x7e755f,0xb39873,0x8b8068];regions.forEach((r,i)=>{const p=new THREE.Vector3(Number(r.x),Number(r.y),Number(r.z));const scale=brainShape(p.x,p.y,p.z);const geo=new THREE.IcosahedronGeometry(.57*scale,3);const pos=geo.attributes.position;for(let j=0;j<pos.count;j++){const v=new THREE.Vector3().fromBufferAttribute(pos,j);const n=.035*Math.sin(v.x*13+i)+.025*Math.cos(v.y*17-i)+.018*Math.sin(v.z*19);v.multiplyScalar(1+n);pos.setXYZ(j,v.x,v.y,v.z)}geo.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({color:palette[i%palette.length],roughness:.72,metalness:.06,transparent:true,opacity:.93,emissive:palette[i%palette.length],emissiveIntensity:.32});const mesh=new THREE.Mesh(geo,mat);mesh.position.copy(p);mesh.userData.region=r;brainGroup.add(mesh);meshes.push(mesh)});links.forEach(l=>{const a=regions.find(r=>r.id===l.from_region_id),b=regions.find(r=>r.id===l.to_region_id);if(!a||!b)return;const points=[new THREE.Vector3(Number(a.x),Number(a.y),Number(a.z)),new THREE.Vector3(Number(b.x),Number(b.y),Number(b.z))];const geo=new THREE.BufferGeometry().setFromPoints(points);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x9f8a62,transparent:true,opacity:.18+Number(l.weight)*.3}));lineGroup.add(line)});lineGroup.visible=false;}
function buildTrajectories(){trajectoryGroup.clear();trajectories.slice(0,8).forEach((trajectory,index)=>{const coords=(trajectory.points||[]).map(p=>p?.projection?.coordinates).filter(c=>Array.isArray(c)&&c.length===3&&c.every(Number.isFinite)).map(c=>new THREE.Vector3(c[0]*2.8,c[1]*2.8,c[2]*2.8));if(!coords.length)return;const color=[0xc9ad70,0x8fa7a0,0xa98674,0x7f8ca6][index%4];coords.forEach((p,i)=>{const latest=i===coords.length-1;const sphere=new THREE.Mesh(new THREE.SphereGeometry(latest ? .13 : .07,18,18),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:latest ? .8 : .3}));sphere.position.copy(p);trajectoryGroup.add(sphere)});if(coords.length>1){const curve=new THREE.CatmullRomCurve3(coords);trajectoryGroup.add(new THREE.Mesh(new THREE.TubeGeometry(curve,Math.max(16,coords.length*8),.025,8,false),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.45,transparent:true,opacity:.74})))}});trajectoryGroup.visible=false;}

function renderTrajectoryInspector(){const latest=trajectories[0];if(!latest){$('inspector').innerHTML='<div class="empty-state"><div class="ring">T</div><h2>No observed path yet</h2><p>The first completed Wonder Mind run creates a state. A trajectory appears only after at least two time-indexed states exist.</p></div>';return}const points=latest.points||[];$('inspector').innerHTML=`<div class="region-head"><span class="number">${escapeHtml(latest.projection_id)}</span><h2>Observed trajectory</h2><div class="question">A path through a controlled projection—not a forecast.</div><p class="purpose">${escapeHtml(latest.epistemic_note)}</p></div><div class="metrics"><div class="metric"><b>${points.length}</b><span>STATES</span></div><div class="metric"><b>${Math.round(Number(latest.coverage)*100)}%</b><span>COVERAGE</span></div><div class="metric"><b>${Math.round(Number(latest.confidence)*100)}%</b><span>CONFIDENCE</span></div></div><div class="section"><h3>Causal status</h3><div class="guardrail">${escapeHtml(latest.causal_status)}</div></div><div class="section"><h3>Interpretive discipline</h3><p class="purpose">Movement may be new evidence, context variation, correction of the model, or real change. Geometry alone cannot decide which.</p></div>`;}

const GLYPH_PATHS={PROGRAM:'M32 5L58 32 32 59 6 32Z',OBSERVE:'M5 32Q32 7 59 32Q32 57 5 32ZM32 24A8 8 0 1 0 32 40A8 8 0 1 0 32 24',INFER:'M8 10Q22 32 32 32Q42 32 56 54M8 54Q22 32 32 32Q42 32 56 10',HYPOTHESIS:'M49 22Q41 8 24 13Q7 19 12 37Q17 54 36 50Q51 47 50 33Q48 23 36 23Q27 23 27 32Q27 39 34 39',PREDICT:'M8 32H42M32 18L48 32 32 46M48 32H58',JUDGE:'M32 8V53M12 22H52M18 22L10 40H26ZM46 22L38 40H54Z',SUPPORT:'M8 16V34Q8 48 22 48H42Q56 48 56 34V16',CONTRADICT:'M10 12L54 52M54 12L10 52M8 32Q32 5 56 32Q32 59 8 32',ALTERNATIVE:'M32 56V31M32 31L14 12M32 31L50 12M14 12V24M50 12V24',UNCERTAINTY:'M47 14A22 22 0 0 0 14 45M17 51A22 22 0 0 0 51 48',TIME:'M9 15H55M14 32H50M20 49H44',DYAD:'M39 32A16 16 0 1 1 23 16A16 16 0 0 1 39 32ZM25 32A16 16 0 1 0 41 16A16 16 0 0 0 25 32Z',BRANCH:'M32 56V28M32 28L12 10M32 28V8M32 28L52 10',BOUNDARY:'M10 54V10H54V54M20 54V28H44V54',CORRECT:'M52 18H25Q10 18 10 34Q10 50 27 50H42M34 42L42 50 34 58',ABSTAIN:'M10 16H54V48H10ZM16 32H48',CLAIM:'M32 10A22 22 0 1 0 32 54A22 22 0 1 0 32 10ZM32 27A5 5 0 1 0 32 37A5 5 0 1 0 32 27',EVIDENCE_REF:'M32 8V34M32 34L14 54M32 34L32 56M32 34L50 54',CHANGE_CONDITION:'M10 20H34V44H54M44 34L54 44 44 54',CONFIDENCE:'M32 7A25 25 0 1 0 32 57A25 25 0 1 0 32 7ZM32 18A14 14 0 1 0 32 46A14 14 0 1 0 32 18ZM32 28A4 4 0 1 0 32 36A4 4 0 1 0 32 28'};
function glyphSvg(op){const d=GLYPH_PATHS[op]||GLYPH_PATHS.UNCERTAINTY;return `<svg viewBox="0 0 64 64" aria-hidden="true"><path d="${d}" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function renderGlyphMode(){const latest=glyphPrograms[0],tokens=latest?.tokens?.length?latest.tokens:glyphLexicon.map(g=>({op:g.operator,glyph:g.glyph_code}));$('glyphOverlay').innerHTML=tokens.slice(0,64).map(t=>`<div class="glyph-card" title="${escapeHtml(t.op)} · ${escapeHtml(t.glyph)}">${glyphSvg(t.op)}<span>${escapeHtml(t.op)}</span></div>`).join('');$('inspector').innerHTML=latest?`<div class="region-head"><span class="number">${escapeHtml(latest.language_version)}</span><h2>Reversible program</h2><div class="question">${escapeHtml(latest.purpose)}</div><p class="purpose">The visible marks are a rendering of canonical semantics, not a replacement for them.</p></div><div class="metrics"><div class="metric"><b>${latest.tokens.length}</b><span>TOKENS</span></div><div class="metric"><b>${latest.reversible?'YES':'NO'}</b><span>REVERSIBLE</span></div><div class="metric"><b>${escapeHtml(latest.source_hash.slice(0,6))}</b><span>HASH</span></div></div><div class="section"><h3>Language rule</h3><div class="guardrail">A glyph is valid only if it expands back into the same claim, evidence, confidence, alternatives, correction conditions and constitutional boundary.</div></div>`:'<div class="empty-state"><div class="ring">W</div><h2>Experimental lexicon</h2><p>No judgment program exists yet. The registered operators are shown in the field; the first completed inference will compile into a reversible sequence.</p></div>';}
function focusRegion(r){if(!controls||!camera)return;controls.autoRotate=false;const target=new THREE.Vector3(Number(r.x),Number(r.y),Number(r.z));controls.target.copy(target);const dir=camera.position.clone().sub(target).normalize();camera.position.copy(target.clone().add(dir.multiplyScalar(7.2)));}
function onPick(e){const rect=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-rect.left)/rect.width)*2-1;pointer.y=-((e.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes,false)[0];if(hit)selectRegion(hit.object.userData.region)}
function resize(){const el=$('brain').parentElement,w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}
boot().catch(e=>{console.error(e);authError.textContent='Wonder Mind could not initialize.'});
