window.WonderOperations=function({api,esc,mount,page,heading,statusEl,error,toast}){
 const request=(action,extra={})=>api('/api/operations',{action,...extra});
 async function render(){
  const d=await request('load');
  mount(page(`${heading('WONDER / Operations','Careful review.<br><em>Accountable decisions.</em>')}${statusEl()}<p>This restricted workspace contains only operational records. Portrait review does not verify identity or guarantee anyone’s safety.</p>
  <h2>Portrait review</h2><div class="account-grid">${d.photos.map(p=>`<form class="ops-form" data-operation="photo"><input type="hidden" name="id" value="${esc(p.id)}"><img src="/api/photos?id=${esc(p.id)}" alt="Portrait submitted for review" style="width:240px;max-height:320px;object-fit:contain"><p>${esc(d.members.find(m=>m.id===p.user_id)?.name||'Member')}</p><label class="field">Outcome<select name="status"><option value="rejected">Needs a new photograph</option><option value="approved">Approved for a shared portrait</option></select></label><label class="field">Note to the member<textarea name="note" maxlength="500"></textarea></label><button class="btn">Apply review</button></form>`).join('')||'<p>No photographs awaiting review.</p>'}</div>
  <h2>Member access</h2><p>Approve only adults included in the controlled Dallas cohort. This gives access; the member must separately choose to become available.</p>${d.members.map(m=>`<form class="ops-form memory" data-operation="cohort"><input type="hidden" name="user_id" value="${esc(m.id)}"><input type="hidden" name="cohort" value="dallas-beta"><p>${esc(m.name||'Account essentials incomplete')} · ${esc(m.city||'City not added')}</p><label class="check-label"><input name="enabled" type="checkbox" ${m.cohort?.enabled?'checked':''}><span>Dallas cohort access</span></label><button class="btn secondary">Save access</button></form>`).join('')}
  <h2>Support and safety</h2>${d.reports.map(r=>`<form class="ops-form memory" data-operation="report"><input type="hidden" name="id" value="${esc(r.id)}"><p>${esc(r.reason)}</p><p class="small">${esc(r.created_at)} · ${esc(r.status)}</p><label class="field">Status<select name="status"><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option></select></label><button class="btn secondary">Save review status</button></form>`).join('')||'<p>No open reports.</p>'}
  <h2>Pending deletion</h2>${d.deletions.map(d=>`<form class="ops-form memory" data-operation="retry_deletion"><input type="hidden" name="user_id" value="${esc(d.user_id)}"><p>Requested ${esc(d.requested_at)}. Active access is withdrawn.</p><button class="btn secondary">Retry removal</button></form>`).join('')||'<p>No pending removals.</p>'}<button class="text-btn" data-action="home">Return to Home</button>`));
 }
 document.addEventListener('submit',e=>{if(!e.target.matches('.ops-form'))return;e.preventDefault();e.stopImmediatePropagation();const form=e.target,b=form.querySelector('button');if(b.disabled)return;b.disabled=true;const p=Object.fromEntries(new FormData(form));if(form.dataset.operation==='cohort')p.enabled=p.enabled==='on';request(form.dataset.operation,p).then(()=>{toast('Saved.');return render();}).catch(x=>error(x.message)).finally(()=>b.disabled=false);},true);
 return {render};
};
