/* The photograph is displaced in real time; taps produce waves in its surface. */
window.WonderPool={mount(host){
 if(!host||document.documentElement.classList.contains('quiet-motion'))return()=>{};const surface=host.querySelector('.pool-surface');let stopped=false,frame;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');const canvas=document.createElement('canvas');canvas.setAttribute('aria-hidden','true');host.prepend(canvas);
 const gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power'});
 const ring=e=>{if(reduced.matches)return;const r=host.getBoundingClientRect();const x=e.clientX?e.clientX-r.left:r.width/2,y=e.clientY?e.clientY-r.top:r.height/2;const el=document.createElement('span');el.className='ripple-ring';el.style.left=x+'px';el.style.top=y+'px';host.append(el);setTimeout(()=>el.remove(),2400);return [x/r.width,1-y/r.height]};
 if(!gl){surface?.addEventListener('click',ring);return()=>surface?.removeEventListener('click',ring)}
 const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error('Water shader unavailable');return s};
 try{
 const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,'attribute vec2 p; varying vec2 v; void main(){v=(p+1.)*.5;gl_Position=vec4(p,0.,1.);}'));
 gl.attachShader(p,shader(gl.FRAGMENT_SHADER,`precision mediump float; varying vec2 v; uniform sampler2D image; uniform float time; uniform vec2 aspect; uniform vec3 wave[6]; void main(){vec2 uv=v;uv.x=.5+(uv.x-.5)*aspect.x;uv.y=.5+(uv.y-.5)*aspect.y;vec2 flow=vec2(sin(uv.y*19.+time*.24),cos(uv.x*21.+time*.19))*.002;for(int i=0;i<6;i++){float age=time-wave[i].z;vec2 delta=v-wave[i].xy;float d=length(delta*vec2(1.,.85));float envelope=exp(-pow((d-age*.19)*9.,2.))*exp(-age*.6);if(age>0.&&age<4.)flow+=normalize(delta+vec2(.0001))*sin(d*65.-age*15.)*.014*envelope;}vec3 color=texture2D(image,uv+flow).rgb;color=mix(color,vec3(dot(color,vec3(.299,.587,.114))),.2);gl_FragColor=vec4(color*vec3(.77,.85,.72),1.);}`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error('Water program unavailable');gl.useProgram(p);
 const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(p,'p');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);
 const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 const t=gl.getUniformLocation(p,'time'),a=gl.getUniformLocation(p,'aspect'),w=gl.getUniformLocation(p,'wave[0]');const waves=new Float32Array(18).fill(-100);let pointer=0;const start=performance.now();
 const click=e=>{const xy=ring(e);if(!xy)return;waves[pointer*3]=xy[0];waves[pointer*3+1]=xy[1];waves[pointer*3+2]=(performance.now()-start)/1000;pointer=(pointer+1)%6};surface?.addEventListener('click',click);
 const img=new Image();img.src='assets/water.jpg';img.onload=()=>{if(stopped)return;gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);const draw=now=>{if(stopped)return;const r=host.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,1.5);const width=Math.max(1,Math.floor(r.width*ratio)),height=Math.max(1,Math.floor(r.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,canvas.width,canvas.height);const ar=r.width/r.height,ir=img.width/img.height;gl.uniform2f(a,ar<ir?ar/ir:1,ar<ir?1:ir/ar);gl.uniform1f(t,reduced.matches?0:(now-start)/1000);gl.uniform3fv(w,waves);gl.drawArrays(gl.TRIANGLES,0,6);if(!reduced.matches)frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw)};
 return()=>{stopped=true;cancelAnimationFrame(frame);surface?.removeEventListener('click',click);gl.getExtension('WEBGL_lose_context')?.loseContext()};
 }catch{canvas.remove();surface?.addEventListener('click',ring);return()=>surface?.removeEventListener('click',ring)}
}};
