// Wonder Mirror Engine v2
// The Elements gather signals. Mirror interprets relationships between them.
// This is a product reflection layer, not a clinical or diagnostic system.

const LABELS={cognitive_systemizing:'structured thinking',cognitive_contextual:'context-sensitive thinking',ambiguity_tolerance:'comfort with ambiguity',decisiveness:'decisiveness',novelty_orientation:'novelty',social_initiation:'social initiation',emotional_intensity:'emotional intensity',structure_preference:'structure',autonomy_need:'autonomy',closeness_need:'closeness',reassurance_need:'relational reassurance',vulnerability_openness:'vulnerability',conflict_directness:'directness in conflict',repair_orientation:'repair',reciprocity_sensitivity:'reciprocity',trust_baseline:'baseline trust',value_family:'family',value_achievement:'achievement',value_meaning:'meaning',value_freedom:'freedom',value_stability:'stability',value_knowledge:'knowledge',value_service:'service',value_influence:'influence',value_beauty:'beauty',value_loyalty:'loyalty',recognition_need:'recognition',competence_identity:'competence',distinctiveness_need:'distinctiveness',belonging_need:'belonging',stress_control:'regaining control',stress_withdrawal:'withdrawing',stress_accommodation:'accommodating others',stress_intellectualization:'analyzing emotion'};
const DOMAINS={cognitive:['cognitive_systemizing','cognitive_contextual','ambiguity_tolerance','decisiveness'],temperament:['novelty_orientation','social_initiation','emotional_intensity','structure_preference'],relationship:['autonomy_need','closeness_need','reassurance_need','vulnerability_openness','conflict_directness','repair_orientation','reciprocity_sensitivity','trust_baseline'],values:['value_family','value_achievement','value_meaning','value_freedom','value_stability','value_knowledge','value_service','value_influence','value_beauty','value_loyalty'],identity:['recognition_need','competence_identity','distinctiveness_need','belonging_need'],stress:['stress_control','stress_withdrawal','stress_accommodation','stress_intellectualization']};
const ELEMENT_DIMENSIONS={
 Earth:['structure_preference','value_family','value_stability','value_beauty','stress_control','competence_identity'],
 Water:['emotional_intensity','closeness_need','reassurance_need','vulnerability_openness','reciprocity_sensitivity','trust_baseline','repair_orientation'],
 Fire:['novelty_orientation','value_achievement','value_freedom','value_influence','conflict_directness','decisiveness'],
 Air:['cognitive_systemizing','cognitive_contextual','ambiguity_tolerance','decisiveness','social_initiation','value_knowledge'],
 Ether:['value_meaning','distinctiveness_need','belonging_need','competence_identity','value_loyalty','value_service']
};

function confidenceWeight(evidence){return 1-Math.exp(-Math.max(0,Number(evidence||0))/1.6)}
function scored(model,keys){const d=model.dimensions||{},e=model.evidence||{};return keys.map(k=>({key:k,value:Number(d[k]||0),evidence:Number(e[k]||0),confidence:confidenceWeight(e[k])})).sort((a,b)=>(b.confidence*Math.abs(b.value))-(a.confidence*Math.abs(a.value)));}
function high(model,domain,count=3){return scored(model,DOMAINS[domain]||[]).filter(x=>x.evidence>0&&Math.abs(x.value)>=.16).slice(0,count)}
function weak(model,count=3){const e=model.evidence||{};return Object.keys(LABELS).map(k=>({key:k,evidence:Number(e[k]||0),confidence:confidenceWeight(e[k])})).sort((a,b)=>a.confidence-b.confidence).slice(0,count)}
function phrase(signal){if(!signal)return'';const label=LABELS[signal.key]||signal.key;if(signal.value>.15)return label;if(signal.value<-.15){const opposites={autonomy_need:'interdependence',closeness_need:'more relational space',structure_preference:'flexibility',novelty_orientation:'familiarity and continuity',conflict_directness:'a less confrontational conflict style',reassurance_need:'low reassurance needs',social_initiation:'a more observant social style',stress_withdrawal:'staying engaged under pressure',stress_control:'tolerating reduced control',recognition_need:'low dependence on recognition'};return opposites[signal.key]||`less emphasis on ${label}`}return label}
function cap(s){return s?s[0].toUpperCase()+s.slice(1):s}

function elementProfiles(model){const out={};for(const [element,keys] of Object.entries(ELEMENT_DIMENSIONS)){const top=scored(model,keys).filter(x=>x.evidence>0&&Math.abs(x.value)>=.14).slice(0,3);const evidence=keys.reduce((n,k)=>n+Number(model.evidence?.[k]||0),0);out[element]={element,signals:top,confidence:Math.round(confidenceWeight(evidence/Math.max(1,keys.length))*100)/100,summary:top.length?`${cap(phrase(top[0]))}${top[1]?` alongside ${phrase(top[1])}`:''}.`:'Wonder has limited evidence here.'};}return out}

function crossElementPatterns(model){const d=model.dimensions||{},e=model.evidence||{};const enough=(...keys)=>keys.every(k=>Number(e[k]||0)>0);const rules=[
 {elements:['Earth','Fire'],keys:['value_stability','value_freedom'],when:()=>d.value_stability>.22&&d.value_freedom>.22,title:'Roots and range',body:'Part of you appears to want a stable base while another part strongly protects freedom and movement. Compatibility may depend less on choosing one than on finding a life structure that can hold both.'},
 {elements:['Water','Fire'],keys:['closeness_need','autonomy_need'],when:()=>d.closeness_need>.24&&d.autonomy_need>.24,title:'Closeness without absorption',body:'You appear to want meaningful intimacy and meaningful independence at the same time. The tension is not whether you want love, but what kind of closeness still lets you remain fully yourself.'},
 {elements:['Water','Fire'],keys:['reassurance_need','autonomy_need'],when:()=>d.reassurance_need>.24&&d.autonomy_need>.24,title:'Independent, but not indifferent',body:'You may identify strongly with autonomy while still registering changes in an important bond quickly. Reliable connection may matter more to you than your self-image of independence initially suggests.'},
 {elements:['Water','Fire'],keys:['closeness_need','stress_withdrawal'],when:()=>d.closeness_need>.24&&d.stress_withdrawal>.24,title:'You may retreat when closeness matters most',body:'Connection appears important to you, but pressure may increase your instinct to pull away. That gap between relational desire and stress behavior is more informative than either trait alone.'},
 {elements:['Earth','Fire'],keys:['competence_identity','stress_control'],when:()=>d.competence_identity>.24&&d.stress_control>.24,title:'Competence can become control',body:'Capability looks central to your identity. Under uncertainty, taking charge may be effective, but Wonder would watch whether control also becomes protection from having to remain inside uncertainty.'},
 {elements:['Air','Ether'],keys:['cognitive_systemizing','cognitive_contextual'],when:()=>d.cognitive_systemizing>.24&&d.cognitive_contextual>.24,title:'Structure without simplification',body:'You seem to use systems to understand complexity without wanting those systems to erase nuance. That relationship between structure and context may be more characteristic than either label on its own.'},
 {elements:['Water','Ether'],keys:['vulnerability_openness','closeness_need'],when:()=>d.vulnerability_openness<-.15&&d.closeness_need>.24,title:'Wanting depth is not the same as finding disclosure easy',body:'Meaningful intimacy appears important, while raw exposure may come less naturally. Wonder would separate your desire for closeness from your comfort with every mechanism that creates it.'},
 {elements:['Fire','Ether'],keys:['value_achievement','value_meaning'],when:()=>d.value_achievement>.25&&d.value_meaning>.25,title:'Achievement has to mean something',body:'Ambition appears real, but achievement alone may not satisfy you. You seem more likely to remain engaged when what you build also feels personally or philosophically significant.'},
 {elements:['Earth','Water'],keys:['value_family','autonomy_need'],when:()=>d.value_family>.25&&d.autonomy_need>.25,title:'Belonging without surrendering authorship',body:'Family or enduring bonds appear important, yet so does the ability to direct your own life. The healthiest version may require belonging that does not demand self-erasure.'}
 ];return rules.filter(r=>enough(...r.keys)&&r.when()).map(r=>({...r,strength:Math.min(...r.keys.map(k=>Math.abs(Number(d[k]||0))*confidenceWeight(e[k]))) })).sort((a,b)=>b.strength-a.strength)}

function buildMirror(model,archetypes=[],context={}){
 const cog=high(model,'cognitive',2),rel=high(model,'relationship',3),vals=high(model,'values',3),identity=high(model,'identity',2),stress=high(model,'stress',2),temp=high(model,'temperament',2);const primary=archetypes[0]||null,secondary=archetypes[1]||null;const elements=elementProfiles(model),patterns=crossElementPatterns(model),leadPattern=patterns[0]||null;const uncertain=weak(model,3);
 const cogLead=cog[0],relLead=rel[0],valLead=vals[0],idLead=identity[0],stressLead=stress[0];
 let move='Wonder is still learning how you organize complexity.';if(cogLead)move=`${cap(phrase(cogLead))} is one of the clearest signals in how you make sense of things.${cog[1]?` ${cap(phrase(cog[1]))} appears alongside it, which keeps the pattern from collapsing into a single cognitive style.`:''}`;
 let drive='Wonder is still separating what you value from what you simply do well.';if(valLead)drive=`${cap(phrase(valLead))} currently carries the strongest value signal.${idLead?` Your identity also appears meaningfully organized around ${phrase(idLead)}, so choices touching both are likely to feel unusually consequential.`:''}`;
 let relationship='Wonder does not yet have enough converging relationship evidence to make a strong claim.';if(relLead)relationship=`${cap(phrase(relLead))} is the clearest relationship signal so far.${rel[1]?` ${cap(phrase(rel[1]))} also matters, suggesting your best relationships may need to satisfy more than one need at once.`:''}`;
 let pressure='Wonder still has limited evidence about what changes under pressure.';if(stressLead)pressure=`Under pressure, ${phrase(stressLead)} appears more likely to intensify.${stress[1]?` A secondary pattern of ${phrase(stress[1])} may appear depending on whether the threat feels practical or relational.`:''}`;
 const coverage=Math.max(0,Math.min(1,Number(model.coverage||0))),gap=primary&&secondary?Math.max(0,Number(primary.score||0)-Number(secondary.score||0)):0;
 return{primary,secondary,archetype_confidence:Math.round(Math.min(1,(coverage*.62)+(gap*.75))*100)/100,headline:leadPattern?.title||primary?.essence||'A pattern is emerging.',move_title:'How your mind organizes experience',move,drive_title:'What carries weight',drive,relationship_title:'How you move toward another person',relationship,pressure_title:'What changes under pressure',pressure,tension_title:leadPattern?.title||'The pattern is not perfectly tidy',tension:leadPattern?.body||'Wonder sees enough variation to avoid reducing you to one clean trait. The places where your answers pull in different directions may be more useful than the easiest label.',uncertain:uncertain.map(x=>LABELS[x.key]||x.key),evidence_coverage:coverage,elements,patterns:patterns.map(({title,body,elements,strength})=>({title,body,elements,strength:Math.round(strength*100)/100})),signals:{cognitive:cog,relationship:rel,values:vals,identity,stress,temperament:temp},basis:{response_count:Number(context.response_count||0),quality:context.quality||null,principle:'The Elements gather signals. Mirror interprets relationships between them.'}};
}

module.exports={buildMirror,LABELS,DOMAINS,ELEMENT_DIMENSIONS,elementProfiles,crossElementPatterns,confidenceWeight};