// Wonder Person Model v2.2
// Product psychometric instrument for resonance + compatibility inference.
// Not a clinical or currently validated diagnostic instrument.

const DIMENSIONS={
 cognitive_systemizing:{domain:'cognitive'},cognitive_contextual:{domain:'cognitive'},ambiguity_tolerance:{domain:'cognitive'},decisiveness:{domain:'cognitive'},novelty_orientation:{domain:'temperament'},social_initiation:{domain:'temperament'},emotional_intensity:{domain:'temperament'},structure_preference:{domain:'temperament'},
 autonomy_need:{domain:'relationship'},closeness_need:{domain:'relationship'},reassurance_need:{domain:'relationship'},vulnerability_openness:{domain:'relationship'},conflict_directness:{domain:'relationship'},repair_orientation:{domain:'relationship'},reciprocity_sensitivity:{domain:'relationship'},trust_baseline:{domain:'relationship'},
 value_family:{domain:'values'},value_achievement:{domain:'values'},value_meaning:{domain:'values'},value_freedom:{domain:'values'},value_stability:{domain:'values'},value_knowledge:{domain:'values'},value_service:{domain:'values'},value_influence:{domain:'values'},value_beauty:{domain:'values'},value_loyalty:{domain:'values'},
 recognition_need:{domain:'identity'},competence_identity:{domain:'identity'},distinctiveness_need:{domain:'identity'},belonging_need:{domain:'identity'},
 stress_control:{domain:'stress'},stress_withdrawal:{domain:'stress'},stress_accommodation:{domain:'stress'},stress_intellectualization:{domain:'stress'}
};
const O=(label,w)=>({label,w});
const S=(id,section,prompt,options)=>({id,section,type:'single',prompt,options});
const L=(id,section,prompt,dimension,anchors=['Not at all','Extremely'])=>({id,section,type:'scale',prompt,anchors,scale:{[dimension]:1}});
const ITEMS=[
S('cog_complexity','Instinct','When something is genuinely complicated, which response is most natural?',[O('I look for a structure that makes the complexity manageable.',{cognitive_systemizing:.85,structure_preference:.2}),O('I stay with contradictions until I understand the context.',{cognitive_contextual:.85,ambiguity_tolerance:.35}),O('I move between both: structure helps, but I resist forcing a clean answer too early.',{cognitive_systemizing:.45,cognitive_contextual:.45,ambiguity_tolerance:.25}),O('It depends heavily on what kind of problem it is.',{cognitive_contextual:.4,ambiguity_tolerance:.4})]),
S('cog_uncertainty','Instinct','You need to make an important decision before you have all the information. What is most like you?',[O('Make the best call available and update quickly.',{decisiveness:.8,ambiguity_tolerance:.55}),O('Keep gathering evidence until uncertainty is meaningfully lower.',{decisiveness:-.35,structure_preference:.35,ambiguity_tolerance:-.3}),O('Build several plausible interpretations and compare them.',{cognitive_systemizing:.5,cognitive_contextual:.45}),O('Follow what feels internally coherent even if I cannot fully articulate why yet.',{cognitive_contextual:.35,ambiguity_tolerance:.25})]),
S('cog_disagreement','Instinct','Someone intelligent makes a strong case against something you believe. Your first internal response is closest to…',[O('Curiosity about what they may see that I do not.',{cognitive_contextual:.5,ambiguity_tolerance:.35}),O('Testing their argument for weak points.',{cognitive_systemizing:.55,conflict_directness:.2}),O('Defending my position until the evidence changes my mind.',{conflict_directness:.4,decisiveness:.3}),O('Holding both possibilities open for a while.',{ambiguity_tolerance:.6,cognitive_contextual:.35})]),
S('cog_explanation','Instinct','When you finally understand something difficult, what is most satisfying?',[O('I can explain the mechanism clearly.',{cognitive_systemizing:.7,value_knowledge:.25}),O('I understand why it behaves differently in different contexts.',{cognitive_contextual:.7,value_knowledge:.25}),O('I can use the insight to make a better decision.',{decisiveness:.35,competence_identity:.35}),O('It changes the way I see something larger.',{value_meaning:.45,cognitive_contextual:.35})]),
L('ambiguity_scale','Instinct','How comfortable are you leaving an important question unresolved for a while?','ambiguity_tolerance'),
L('decisive_scale','Instinct','Once you have enough information, how quickly do you usually commit to a decision?','decisiveness'),
S('novelty_weekend','Instinct','An unexpected free weekend appears. Which pull is strongest?',[O('Go somewhere or do something new.',{novelty_orientation:.8,value_freedom:.25}),O('Disappear into something I am fascinated by.',{value_knowledge:.45,autonomy_need:.3}),O('Gather people and see where things go.',{social_initiation:.55,closeness_need:.2}),O('Restore order, rest, and enjoy having no demands.',{structure_preference:.4,value_stability:.35})]),
L('novelty_scale','Instinct','How strongly do you need novelty or change to feel fully alive?','novelty_orientation'),
S('social_room','Instinct','You enter a room where you know almost no one. What tends to happen?',[O('I initiate conversations fairly naturally.',{social_initiation:.75}),O('I observe first, then approach whoever interests me.',{social_initiation:.25,cognitive_contextual:.25}),O('I am happiest if one substantial conversation emerges.',{closeness_need:.25,social_initiation:-.1}),O('I usually prefer someone else to create the opening.',{social_initiation:-.55})]),
L('emotion_scale','Instinct','When something matters deeply to you, how intensely do you tend to feel it?','emotional_intensity'),
L('structure_scale','Instinct','How much does having structure or a plan improve your ability to function well?','structure_preference'),
{ id:'identity_feedback',section:'Self',type:'multi',max:3,prompt:'Choose up to three qualities people who know you well would be most likely to emphasize.',options:[O('Strong-minded',{competence_identity:.45,conflict_directness:.2}),O('Warm',{belonging_need:.4,closeness_need:.25}),O('Curious',{value_knowledge:.45,novelty_orientation:.2}),O('Reliable',{structure_preference:.4,value_stability:.3}),O('Independent',{autonomy_need:.5,value_freedom:.3}),O('Intense',{emotional_intensity:.5}),O('Unconventional',{distinctiveness_need:.5,novelty_orientation:.25}),O('Thoughtful',{cognitive_contextual:.35,value_knowledge:.2}),O('Ambitious',{value_achievement:.5,competence_identity:.25}),O('Loyal',{value_loyalty:.5,closeness_need:.15})]},
S('identity_compliment','Self','Which kind of recognition tends to land deepest?',[O('You are exceptionally capable.',{competence_identity:.6,recognition_need:.2}),O('You make people feel deeply cared for.',{belonging_need:.45,closeness_need:.25}),O('You see things other people miss.',{distinctiveness_need:.4,value_knowledge:.35}),O('You have built something remarkable.',{value_achievement:.55,recognition_need:.25}),O('You are completely yourself.',{value_freedom:.4,distinctiveness_need:.4})]),
S('identity_criticism','Self','Which criticism from someone you respect would be hardest to absorb?',[O('You are not as capable as you think.',{competence_identity:.65}),O('You are selfish.',{belonging_need:.45}),O('You are ordinary.',{distinctiveness_need:.55,recognition_need:.2}),O('You are difficult to truly know.',{closeness_need:.25}),O('You do not really know yourself.',{distinctiveness_need:.2})]),
L('recognition_scale','Self','How much does being respected or admired matter to your sense of fulfillment?','recognition_need'),
L('distinct_scale','Self','How important is it to feel that your life reflects something distinctly your own?','distinctiveness_need'),
L('belong_scale','Self','How important is feeling deeply accepted by a community or group of people?','belonging_need'),
L('competence_scale','Self','How central is being capable and effective to your sense of who you are?','competence_identity'),
{ id:'values_rank',section:'Values',type:'rank',max:5,prompt:'Choose the five that matter most to the life you want, then rank them.',options:[{label:'Deep love',dimension:'closeness_need'},{label:'Family',dimension:'value_family'},{label:'Achievement',dimension:'value_achievement'},{label:'Freedom',dimension:'value_freedom'},{label:'Stability',dimension:'value_stability'},{label:'Meaning',dimension:'value_meaning'},{label:'Knowledge',dimension:'value_knowledge'},{label:'Adventure',dimension:'novelty_orientation'},{label:'Service',dimension:'value_service'},{label:'Influence',dimension:'value_influence'},{label:'Beauty',dimension:'value_beauty'},{label:'Loyalty',dimension:'value_loyalty'}]},
S('values_loss','Values','Which loss would feel most like losing the shape of the life you wanted?',[O('Not building or accomplishing something that mattered.',{value_achievement:.7,competence_identity:.25}),O('Not having the depth of love and connection I wanted.',{closeness_need:.7,value_family:.2}),O('Living securely but never feeling fully free.',{value_freedom:.7,autonomy_need:.3}),O('Succeeding without feeling that any of it meant much.',{value_meaning:.75}),O('Living meaningfully but becoming too narrow or repetitive.',{novelty_orientation:.55,value_freedom:.3})]),
S('values_money','Values','Imagine money and status are permanently handled. What impulse would still pull hardest?',[O('Make or build things.',{value_achievement:.35,value_meaning:.25}),O('Learn and understand.',{value_knowledge:.7}),O('Explore and experience.',{novelty_orientation:.65,value_freedom:.25}),O('Serve or improve other people’s lives.',{value_service:.7}),O('Create a rich private life with people I love.',{value_family:.5,closeness_need:.5}),O('Shape institutions, culture, or outcomes at scale.',{value_influence:.7})]),
S('values_beauty','Values','How does beauty function in your life?',[O('It is pleasant, but not central.',{value_beauty:-.25}),O('My surroundings strongly affect how I feel and think.',{value_beauty:.55,emotional_intensity:.15}),O('Beauty feels almost like a form of meaning.',{value_beauty:.7,value_meaning:.25}),O('I care more about function than aesthetics.',{cognitive_systemizing:.25,value_beauty:-.35})]),
S('values_loyalty','Values','When loyalty and truth genuinely conflict, what feels more important?',[O('Tell the truth even if it destabilizes the bond.',{conflict_directness:.4}),O('Protect the person or bond unless the truth is essential.',{value_loyalty:.55,belonging_need:.2}),O('Find a way to preserve both if at all possible.',{repair_orientation:.45,cognitive_contextual:.3}),O('It depends entirely on what the truth would protect or harm.',{cognitive_contextual:.45,ambiguity_tolerance:.25})]),
S('betrayal','Values','Which breach would be hardest for you to repair after?',[O('Being deliberately deceived.',{value_loyalty:.35}),O('Being abandoned when I genuinely needed them.',{closeness_need:.45,reassurance_need:.4}),O('Having something private used against me.',{vulnerability_openness:-.3}),O('Having my agency overridden or being controlled.',{autonomy_need:.65,value_freedom:.4}),O('Repeatedly discovering I mattered less to them than they mattered to me.',{reciprocity_sensitivity:.7,closeness_need:.25})]),
L('family_scale','Values','How central is family, chosen or biological, to the life you ultimately want?','value_family'),
L('achievement_scale','Values','How important is meaningful achievement to the life you ultimately want?','value_achievement'),
L('meaning_scale','Values','How strongly do you need your life to feel meaningful rather than merely pleasant or successful?','value_meaning'),
S('rel_distance','Relationships','Someone you are beginning to care about becomes noticeably quieter for several days. What happens first?',[O('I assume a benign explanation unless I get evidence otherwise.',{trust_baseline:.75,reassurance_need:-.2}),O('I notice quickly and wonder whether something changed between us.',{reassurance_need:.65,reciprocity_sensitivity:.3}),O('I ask directly rather than infer.',{conflict_directness:.65,repair_orientation:.4}),O('I give room but become a little more guarded too.',{autonomy_need:.35,stress_withdrawal:.45}),O('It depends on the established pattern between us.',{cognitive_contextual:.4,trust_baseline:.15})]),
L('rel_closeness','Relationships','In a close relationship, how important is frequent emotional contact to you?','closeness_need'),
L('rel_autonomy','Relationships','How important is it that both partners maintain substantial independent lives?','autonomy_need'),
L('rel_reassurance','Relationships','When you care deeply about someone, how much do changes in their behavior affect your sense of security in the relationship?','reassurance_need'),
L('rel_vulnerability','Relationships','How comfortable are you saying exactly what you feel when doing so gives someone the power to hurt you?','vulnerability_openness'),
S('rel_conflict','Relationships','In serious conflict, what do you most want to accomplish first?',[O('Understand what actually happened.',{repair_orientation:.55,cognitive_contextual:.3}),O('Resolve the concrete problem.',{repair_orientation:.45,cognitive_systemizing:.35}),O('Make sure we still feel emotionally connected.',{closeness_need:.45,reassurance_need:.4}),O('Make sure my position is accurately understood.',{conflict_directness:.45}),O('Get enough distance to think clearly before engaging.',{autonomy_need:.3,stress_withdrawal:.5})]),
L('direct_scale','Relationships','How comfortable are you raising a relationship problem before the other person brings it up?','conflict_directness'),
L('repair_scale','Relationships','After conflict, how strong is your impulse to actively repair the connection rather than simply move on?','repair_orientation'),
L('reciprocity_scale','Relationships','How strongly do you notice imbalances in effort, initiation, affection, or emotional investment?','reciprocity_sensitivity'),
L('trust_scale','Relationships','At the beginning of a promising relationship, how readily do you assume the other person is sincere?','trust_baseline'),
S('rel_dependence','Relationships','A partner begins relying on you much more emotionally. Which response is closest?',[O('I usually feel closer to them.',{closeness_need:.55,autonomy_need:-.15}),O('I care, but too much dependence eventually feels heavy.',{autonomy_need:.45,closeness_need:.1}),O('It feels good if the dependence is reciprocal rather than one-sided.',{reciprocity_sensitivity:.55}),O('I become uncomfortable surprisingly quickly.',{autonomy_need:.6,stress_withdrawal:.25})]),
S('rel_initiation','Relationships','You realize you have initiated nearly every plan with someone for a month. What is most likely?',[O('I stop initiating and see what happens.',{reciprocity_sensitivity:.5,stress_withdrawal:.25}),O('I ask them about the imbalance.',{conflict_directness:.55,repair_orientation:.3}),O('I keep initiating if I genuinely enjoy seeing them.',{autonomy_need:.25,reciprocity_sensitivity:-.2}),O('I feel hurt before deciding what to do.',{emotional_intensity:.3,reassurance_need:.35})]),
S('rel_model','Relationships','A great partnership feels most like…',[O('Two independent lives repeatedly choosing each other.',{autonomy_need:.6,closeness_need:.25}),O('Two lives becoming increasingly intertwined.',{closeness_need:.65,autonomy_need:-.15}),O('Deep interdependence without loss of individuality.',{closeness_need:.5,autonomy_need:.5}),O('A secure home base that makes both people braver in the world.',{trust_baseline:.35,closeness_need:.35,novelty_orientation:.2})]),
S('stress_failure','Under pressure','Something important fails and you were responsible. What tends to happen first?',[O('I analyze the failure until I understand the mechanism.',{stress_intellectualization:.65,cognitive_systemizing:.3}),O('I start fixing what can still be fixed.',{stress_control:.6,decisiveness:.3}),O('I feel the emotional impact before I can think clearly.',{emotional_intensity:.5}),O('I want distance from the situation for a while.',{stress_withdrawal:.65}),O('I become especially attentive to everyone affected.',{stress_accommodation:.55,repair_orientation:.2})]),
S('stress_chaos','Under pressure','When several areas of life become chaotic at once, which change in you is most recognizable?',[O('I become more organized and directive.',{stress_control:.55,structure_preference:.25}),O('I retreat and reduce contact.',{stress_withdrawal:.65}),O('I become more emotionally reactive.',{emotional_intensity:.45}),O('I start taking care of everyone else.',{stress_accommodation:.6}),O('I move into analysis and can become detached from what I feel.',{stress_intellectualization:.65})]),
S('stress_misread','Under pressure','Someone close to you forms an unfair interpretation of your motives. What pulls hardest?',[O('Correct the interpretation immediately.',{stress_control:.35,conflict_directness:.25}),O('Explain once, then let them decide.',{autonomy_need:.35,conflict_directness:.25}),O('It hurts more than I want them to know.',{emotional_intensity:.35,reassurance_need:.2}),O('I become angry that they could think that of me.',{conflict_directness:.35}),O('I detach rather than keep trying to be understood.',{stress_withdrawal:.55})]),
L('stress_control_scale','Under pressure','Under uncertainty, how strongly do you feel compelled to regain control of the situation?','stress_control'),
L('stress_withdraw_scale','Under pressure','When overwhelmed, how strongly do you want to disappear from demands and other people for a while?','stress_withdrawal'),
L('stress_accom_scale','Under pressure','When tension rises, how likely are you to prioritize keeping other people okay over expressing your own needs?','stress_accommodation'),
L('stress_intellect_scale','Under pressure','When emotionally overwhelmed, how likely are you to analyze the feeling instead of simply experiencing it?','stress_intellectualization'),
S('shadow_need','Shadow','Which need is hardest for you to admit openly when it is strong?',[O('I want reassurance.',{reassurance_need:.45}),O('I want help.',{}),O('I want affection.',{closeness_need:.4}),O('I want approval or admiration.',{recognition_need:.55}),O('I want to belong.',{belonging_need:.55}),O('None of these are particularly hard to admit.',{vulnerability_openness:.35})]),
S('shadow_possibility','Shadow','Which possibility about yourself would be most uncomfortable to seriously examine?',[O('I use independence to avoid vulnerability.',{}),O('I care more about admiration than I admit.',{}),O('I sometimes mistake control for competence.',{}),O('I compromise myself to avoid losing people.',{}),O('I intellectualize feelings instead of experiencing them.',{}),O('I need people more than my self-image allows.',{})]),
S('contradiction_known','Shadow','Which statement feels most accurate?',[O('Most people understand me reasonably well.',{vulnerability_openness:.25}),O('Different people know genuinely different versions of me.',{cognitive_contextual:.2,distinctiveness_need:.15}),O('Very few people know me deeply.',{vulnerability_openness:-.2}),O('I am not sure anyone fully knows me.',{vulnerability_openness:-.3})]),
S('contradiction_need','Shadow','When you most want closeness, what are you most likely to do?',[O('Move toward the person and say so.',{vulnerability_openness:.55,closeness_need:.25}),O('Create opportunities for closeness without naming the need directly.',{closeness_need:.35,reassurance_need:.2}),O('Wait to see whether they move toward me first.',{reciprocity_sensitivity:.4,reassurance_need:.3}),O('Become more self-sufficient than usual.',{autonomy_need:.3,stress_withdrawal:.45})])
];
const ARCHETYPES={Architect:{prototype:{cognitive_systemizing:.8,competence_identity:.65,structure_preference:.45,decisiveness:.45,autonomy_need:.3},essence:'Turns complexity into structure and direction.'},Seer:{prototype:{cognitive_contextual:.75,ambiguity_tolerance:.55,value_knowledge:.5,value_meaning:.5},essence:'Lives through pattern, interpretation, and underlying meaning.'},Explorer:{prototype:{novelty_orientation:.8,value_freedom:.7,autonomy_need:.45,ambiguity_tolerance:.4},essence:'Expands through movement, possibility, and discovery.'},Sovereign:{prototype:{value_influence:.6,competence_identity:.7,decisiveness:.65,stress_control:.45,recognition_need:.25},essence:'Creates agency, direction, and consequential outcomes.'},Alchemist:{prototype:{emotional_intensity:.55,value_meaning:.75,vulnerability_openness:.35,cognitive_contextual:.4},essence:'Transforms experience into depth, meaning, and change.'},Devotee:{prototype:{closeness_need:.75,value_loyalty:.65,value_family:.45,reciprocity_sensitivity:.55},essence:'Organizes life around depth of bond and emotional significance.'},Guardian:{prototype:{value_stability:.7,structure_preference:.6,value_loyalty:.55,repair_orientation:.45,value_family:.45},essence:'Creates continuity, reliability, and safety around what matters.'},Maverick:{prototype:{autonomy_need:.75,value_freedom:.7,distinctiveness_need:.6,novelty_orientation:.4},essence:'Protects self-definition and resists inherited scripts.'}};
function emptyModel(){const scores={},evidence={};Object.keys(DIMENSIONS).forEach(k=>{scores[k]=0;evidence[k]=0});return{scores,evidence}}
function add(m,k,v,e=1){if(k in m.scores){m.scores[k]+=v;m.evidence[k]+=e}}
function scoreResponses(responses={}){const m=emptyModel();for(const item of ITEMS){const r=responses[item.id];if(r==null)continue;if(item.type==='single'){const o=item.options[Number(r)];if(o)Object.entries(o.w||{}).forEach(([k,v])=>add(m,k,v))}else if(item.type==='scale'){const n=Math.max(1,Math.min(7,Number(r)));const centered=(n-4)/3;Object.entries(item.scale).forEach(([k,w])=>add(m,k,centered*w))}else if(item.type==='multi'){const arr=Array.isArray(r)?r:[];arr.slice(0,item.max||arr.length).forEach(i=>{const o=item.options[Number(i)];if(o)Object.entries(o.w||{}).forEach(([k,v])=>add(m,k,v))})}else if(item.type==='rank'){const arr=Array.isArray(r)?r:[];const weights=[1,.8,.6,.45,.3];arr.slice(0,item.max||5).forEach((i,rank)=>{const o=item.options[Number(i)];if(o)add(m,o.dimension,weights[rank]||.25)})}}const normalized={};Object.keys(m.scores).forEach(k=>normalized[k]=m.evidence[k]?Math.max(-1,Math.min(1,m.scores[k]/m.evidence[k])):0);return{dimensions:normalized,evidence:m.evidence,coverage:Object.values(m.evidence).filter(Boolean).length/Object.keys(DIMENSIONS).length}}
function archetypeSimilarity(d,p){let sum=0,w=0;for(const[k,target]of Object.entries(p)){const importance=Math.abs(target);sum+=(1-Math.min(2,Math.abs((d[k]||0)-target))/2)*importance;w+=importance}return w?sum/w:0}
function inferArchetypes(model){return Object.entries(ARCHETYPES).map(([name,a])=>({name,score:archetypeSimilarity(model.dimensions,a.prototype),essence:a.essence})).sort((a,b)=>b.score-a.score)}
function publicItemBank(){return ITEMS.map(({options,...i})=>({...i,options:options?.map(({w,dimension,...o})=>o)}))}
module.exports={DIMENSIONS,ITEMS,ARCHETYPES,scoreResponses,inferArchetypes,publicItemBank};