const {authUser,rest}=require('../../lib/supabase-server');
const {compatibility,ENGINE_VERSION,ageFromDob}=require('../../lib/matching-engine-v4');
const {applyRelationalLearning}=require('../../lib/matching-learning');

async function latestModel(userId){
 const rows=await rest(`/person_model_snapshots?user_id=eq.${encodeURIComponent(userId)}&select=*&order=created_at.desc&limit=1`,{admin:true});const row=rows[0];if(!row)return null;
 return{dimensions:row.scores||{},evidence:row.confidence?.evidence||{},coverage:Number(row.confidence?.coverage||0),archetypes:row.archetypes||[],model_version:row.model_version,mirror_basis:row.evidence?.mirror_basis||null,foundations:row.evidence?.foundations||{},psychological_architecture:row.evidence?.psychological_architecture||null,archetype_roles:row.evidence?.archetype_roles||null,archetype_version:row.evidence?.archetype_version||'legacy'};
}
async function latestRelationalSelf(userId){try{const rows=await rest(`/relational_self_snapshots?user_id=eq.${encodeURIComponent(userId)}&select=*&order=created_at.desc&limit=1`,{admin:true});return rows?.[0]||null;}catch{return null;}}
async function birthMap(){try{const rows=await rest('/birth_data?select=user_id,date_of_birth',{admin:true});return Object.fromEntries(rows.map(r=>[r.user_id,r.date_of_birth]));}catch{return{};}}
function enrich(profile,births){const dob=births[profile.user_id]||null;return{...profile,date_of_birth:dob,_age:ageFromDob(dob),location_data:profile.location_data||null};}
async function declinedCandidates(userId){try{const feedback=await rest(`/match_feedback?user_id=eq.${userId}&reaction=eq.decline&select=match_id`,{admin:true});const ids=feedback.map(x=>x.match_id).filter(Boolean);if(!ids.length)return new Set();const encoded=ids.map(id=>`"${id}"`).join(',');const rows=await rest(`/matches?id=in.(${encoded})&select=matched_user_id`,{admin:true});return new Set(rows.map(r=>r.matched_user_id));}catch{return new Set();}}
async function react(userId,body){const matchId=body.match_id,reaction=String(body.reaction||'');if(!matchId||!['explore','decline'].includes(reaction))throw new Error('Invalid reaction');const rows=await rest(`/matches?id=eq.${encodeURIComponent(matchId)}&user_id=eq.${userId}&select=id,matched_user_id`,{admin:true});if(!rows[0])throw new Error('Match not found');await rest('/match_feedback',{method:'POST',admin:true,prefer:'return=minimal',body:{match_id:matchId,user_id:userId,reaction,notes:String(body.notes||'').trim()||null}});await rest(`/matches?id=eq.${encodeURIComponent(matchId)}&user_id=eq.${userId}`,{method:'PATCH',admin:true,prefer:'return=minimal',body:{status:reaction==='explore'?'exploring':'declined'}});return{ok:true,reaction,candidate_user_id:rows[0].matched_user_id};}

function convictionRank(v){return v==='strong'?4:v==='promising'?3:v==='exploratory'?2:v==='weak'?1:0;}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});
 const auth=String(req.headers.authorization||''),token=auth.startsWith('Bearer ')?auth.slice(7):'',user=await authUser(token);if(!user?.id)return res.status(401).json({error:'Authentication required.'});
 try{
  if(req.body?.action==='reaction')return res.status(200).json(await react(user.id,req.body));
  const births=await birthMap(),declined=await declinedCandidates(user.id);const meRaw=(await rest(`/profiles?user_id=eq.${user.id}&select=*`,{admin:true}))[0]||{},meProfile=enrich(meRaw,births),meModel=await latestModel(user.id),meRelational=await latestRelationalSelf(user.id);if(!meModel)return res.status(409).json({error:'Complete the Wonder assessment before generating introductions.'});
  const candidates=(await rest(`/profiles?user_id=neq.${user.id}&select=*`,{admin:true})).filter(p=>!declined.has(p.user_id)).map(p=>enrich(p,births)),eligible=[],rejected=[];
  for(const profile of candidates){const [model,relational]=await Promise.all([latestModel(profile.user_id),latestRelationalSelf(profile.user_id)]);if(!model)continue;const base=compatibility({profile:meProfile,model:meModel},{profile,model});const result=applyRelationalLearning(base,meRelational,relational);
   await rest('/compatibility_scores?on_conflict=user_id,candidate_user_id,engine_version',{method:'POST',admin:true,prefer:'resolution=merge-duplicates,return=minimal',body:{user_id:user.id,candidate_user_id:profile.user_id,engine_version:ENGINE_VERSION,eligible:result.eligible,score:result.score,confidence:result.confidence,components:{...(result.components||{}),conviction:result.conviction,learning:result.learning||null,hard_details:result.hard_details||{},archetype_version:result.archetype_version||null},hard_conflicts:result.hard_conflicts||[],rationale:result.rationale||{}}});
   if(result.eligible)eligible.push({candidate_user_id:profile.user_id,profile,result});else rejected.push({candidate_user_id:profile.user_id,reasons:result.hard_conflicts,details:result.hard_details});}
  eligible.sort((a,b)=>convictionRank(b.result.conviction)-convictionRank(a.result.conviction)||b.result.score-a.result.score||b.result.confidence-a.result.confidence);
  const chosen=eligible.find(x=>['strong','promising'].includes(x.result.conviction))||null,top=[];
  if(chosen){const {candidate_user_id,profile,result}=chosen;let matchId=null;try{const rows=await rest('/matches?on_conflict=user_id,matched_user_id',{method:'POST',admin:true,prefer:'resolution=merge-duplicates,return=representation',body:{user_id:user.id,matched_user_id:candidate_user_id,score:result.score,rationale:{engine_version:ENGINE_VERSION,archetype_version:result.archetype_version||null,conviction:result.conviction,confidence:result.confidence,components:result.components,learning:result.learning||null,strengths:result.rationale?.strengths||[],tensions:result.rationale?.tensions||[],archetype_pair:result.rationale?.archetype_pair||null,relational_system:result.rationale?.relational_system||null,distance_miles:result.hard_details?.distance_miles??null},status:'suggested'}});matchId=rows?.[0]?.id||null;}catch(e){console.error('persist suggested match',e);}top.push({match_id:matchId,candidate_user_id,first_name:profile.first_name||null,current_city:profile.current_city||null,score:result.score,confidence:result.confidence,conviction:result.conviction,components:result.components,rationale:result.rationale,distance_miles:result.hard_details?.distance_miles??null});}
  return res.status(200).json({engine_version:ENGINE_VERSION,matches:top,evaluated:eligible.length+rejected.length,eligible_count:eligible.length,rejected_count:rejected.length,conviction_required:true,relational_learning_used:!!meRelational});
 }catch(e){console.error('match generation',e);const status=/Invalid reaction|not found/i.test(String(e.message))?400:500;return res.status(status).json({error:status===400?String(e.message):'Unable to generate introductions.'});}
};