const assert=require('node:assert/strict');const J=require('../public-shared/journey');const {catalog,personalizedReport}=require('../lib/archetype-reports');
let w=J.fixture();const pair=(type,actor='alex',payload={})=>w.pair=J.pairEvent(w.pair,{type,payload},actor,w.users);const user=(type,payload={},id='alex')=>w.users[id]=J.privateEvent(w.users[id],{type,payload});
assert.equal(catalog().length,20);for(const r of catalog()){assert.equal(r.sections.length,15);assert.equal(new Set(r.sections.map(s=>s.id)).size,15);assert.ok(r.sections.every(s=>s.body.length>60&&s.support&&s.question&&s.context));}
assert.equal(personalizedReport({},[],{}).lens_status,'unassigned');
assert.throws(()=>J.privateEvent(J.initial(),{type:'basics',payload:{name:'Test',dob:'2020-01-01',city:'Dallas',process:true}}));
assert.throws(()=>pair('message','alex',{body:'too early'}));pair('interest');assert.equal(w.pair.status,'pending');assert.equal(J.pairView(w.pair,'rowan',w.users).myInterest,null);assert.throws(()=>pair('message','alex',{body:'still too early'}));pair('interest','rowan');assert.equal(w.pair.status,'mutual');pair('message','alex',{id:'one',body:'A walk and a gallery?'});pair('message','alex',{id:'one',body:'A walk and a gallery?'});assert.equal(w.pair.messages.length,1);
pair('plan','alex',{when:'2026-10-02T16:00',zone:'America/Chicago',place:'Public gallery'});assert.throws(()=>pair('accept_plan'));pair('accept_plan','rowan');assert.equal(w.pair.plan.status,'confirmed');w.pair.reminders=[{fake:true}];pair('cancel_plan');assert.equal(w.pair.reminders.length,0);assert.equal(w.pair.plan.status,'cancelled');
user('journal',{id:'secret',body:'PRIVATE_A'});assert.ok(!JSON.stringify(J.pairView(w.pair,'rowan',w.users)).includes('PRIVATE_A'));assert.ok(!Object.hasOwn(J.shared(w.users.alex),'dob'));assert.ok(!Object.hasOwn(J.shared(w.users.alex),'journal'));
user('correct',{claim:'thinking',fit:'doesnt',original:'OLD_INFERENCE',revision:'MY_CORRECTION',matching:false});const effective=J.effective({id:'thinking',body:'OLD_INFERENCE'},w.users.alex);assert.equal(effective.body,'MY_CORRECTION');assert.ok(!JSON.stringify(effective).includes('OLD_INFERENCE'));assert.equal(w.users.alex.availability,'paused');assert.throws(()=>pair('message','rowan',{body:'stale screen'}));user('availability',{value:'available'});
user('memory',{id:'m',body:'A possible preference',remember:true,matching:false,context:'One date'});user('forget',{id:'m'});assert.equal(w.users.alex.memories.length,0);user('availability',{value:'available'});user('preferences',{minAge:35,maxAge:45,intention:'A committed relationship',cityRequired:true});assert.throws(()=>pair('message','rowan',{body:'constraints changed'}));
w=J.fixture();pair('block');assert.throws(()=>pair('interest'));assert.equal(J.pairView(w.pair,'rowan',w.users).status,'unavailable');assert.throws(()=>J.pairView(w.pair,'intruder',w.users));
w=J.fixture();user('reflection',{id:'r',attendance:'cancelled',body:'private',answers:{attraction:'yes'}});assert.deepEqual(w.users.alex.reflections[0].answers,{});user('delete');assert.equal(w.users.alex.journal.length,0);assert.equal(w.users.alex.memories.length,0);assert.equal(J.pairView(w.pair,'rowan',w.users).status,'withdrawn');assert.throws(()=>pair('interest'));
console.log('PASS: 300 report sections, adult gate, mutuality, idempotent messages, counterpart acceptance, cancellation, private projection, correction replacement, stale constraints, blocking, deletion.');
