const {SUPABASE_URL,ANON,SECRET,refreshToken,setSessionCookies,clearSessionCookies}=require('../lib/supabase-server');
const {secureApi,cleanText}=require('../lib/api-security');
const attempts=new Map();
function ipKey(req){return String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();}
function allow(req,action){if(action==='refresh'||action==='logout')return true;const now=Date.now(),key=`${ipKey(req)}:${action}`,windowMs=15*60*1000,max=action==='create'?5:20;let b=attempts.get(key)||{start:now,count:0};if(now-b.start>windowMs)b={start:now,count:0};b.count++;attempts.set(key,b);if(attempts.size>2000)for(const [k,v] of attempts)if(now-v.start>windowMs)attempts.delete(k);return b.count<=max;}
async function readJson(response){const text=await response.text();try{return text?JSON.parse(text):{}}catch{return{message:text}}}
async function tokenRequest(grantType,body){const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=${encodeURIComponent(grantType)}`,{method:'POST',headers:{apikey:ANON,Authorization:`Bearer ${ANON}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await readJson(response);if(!response.ok){const e=new Error(data?.msg||data?.message||data?.error_description||'Unable to sign in.');e.status=response.status;throw e;}return data;}
function publicSession(session,extra={}){return{user:session.user||null,expires_in:session.expires_in||3600,token_type:'cookie',...extra};}
async function adminCreate(email,password,phone){const response=await fetch(`${SUPABASE_URL}/auth/v1/admin/users`,{method:'POST',headers:{apikey:SECRET,Authorization:`Bearer ${SECRET}`,'Content-Type':'application/json'},body:JSON.stringify({email,password,email_confirm:true,user_metadata:{phone,wonder_preview:true}})});return{response,data:await readJson(response)};}
async function adminDelete(userId){if(!userId)return;try{await fetch(`${SUPABASE_URL}/auth/v1/admin/users/${encodeURIComponent(userId)}`,{method:'DELETE',headers:{apikey:SECRET,Authorization:`Bearer ${SECRET}`}});}catch(error){console.error('account rollback',error);}}
module.exports=async function handler(req,res){if(!secureApi(req,res))return;if(!SUPABASE_URL||!ANON||!SECRET)return res.status(503).json({error:'Account service unavailable.'});const body=req.body||{},action=String(body.action||'create');if(!allow(req,action))return res.status(429).json({error:'Too many account attempts. Please try again shortly.'});try{if(action==='logout'){clearSessionCookies(res);return res.status(200).json({ok:true});}if(action==='refresh'){const rt=refreshToken(req);if(!rt){clearSessionCookies(res);return res.status(401).json({error:'Session expired.'});}const session=await tokenRequest('refresh_token',{refresh_token:rt});setSessionCookies(res,session);return res.status(200).json(publicSession(session,{action:'refresh'}));}const cleanEmail=cleanText(body.email,320).toLowerCase(),cleanPassword=String(body.password||''),cleanPhone=cleanText(body.phone,40);if(!cleanEmail||cleanPassword.length<10||cleanPassword.length>128)return res.status(400).json({error:'Enter an email and a password between 10 and 128 characters.'});if(action==='signin'){try{const session=await tokenRequest('password',{email:cleanEmail,password:cleanPassword});setSessionCookies(res,session);return res.status(200).json(publicSession(session,{action:'signin'}));}catch(e){return res.status(400).json({error:'Email or password is incorrect.'});}}if(action!=='create')return res.status(400).json({error:'Unknown account action.'});if(cleanPhone.replace(/\D/g,'').length<10)return res.status(400).json({error:'Enter a valid phone number.'});const {response:createResponse,data:created}=await adminCreate(cleanEmail,cleanPassword,cleanPhone);if(!createResponse.ok){const message=String(created?.msg||created?.message||created?.error_description||'');if(/already|registered|exists/i.test(message))return res.status(409).json({error:'An account already exists with this email.',code:'account_exists'});return res.status(400).json({error:'Unable to create account.'});}try{const session=await tokenRequest('password',{email:cleanEmail,password:cleanPassword});setSessionCookies(res,session);return res.status(200).json(publicSession(session,{needs_email_confirmation:false,action:'create'}));}catch(error){await adminDelete(created?.id);console.error('account initial session',error);return res.status(503).json({error:'Your account could not be initialized. Please try again.'});}}catch(error){console.error('account service',error);return res.status(500).json({error:'Unable to reach the account service.'});}};